### ISSUE TITLE
Admin check error

### ISSUE THREAD

**Issue by edvardmokin** [archi-contribs/database-plugin#101]
[Archi](url
[DatabasePlugin.log](https://github.com/archi-contribs/database-plugin/files/4955976/DatabasePlugin.log)
) 4.8
DB Plugin 2.2.8
When click Admin get an error that DB missing the columns/constrain which is not a case. Log file added

![image](https://user-images.githubusercontent.com/54371319/88102258-3cca8300-cb6d-11ea-816a-5e88f2aeb1ce.png)

![image](https://user-images.githubusercontent.com/54371319/88102719-06d9ce80-cb6e-11ea-8695-3dcd11e1c925.png)

**Comment by herve91** [comment]
Hi,

The error is fixed in version 2.2.9 of the plugin.

Best regards
Hervé
