### ISSUE TITLE
Import from Database error dbmodels does not exist

### ISSUE THREAD

**Issue by edvardmokin** [archi-contribs/database-plugin#103]
Archi 4.7
Database plugin 2.2.9

Import model from database gives an error - Invalid object name 'dbmodels' . Screenshot and log attached

![image](https://user-images.githubusercontent.com/54371319/88594065-8e23b800-d02e-11ea-900b-4ad6010e283e.png)
[DatabasePlugin.log](https://github.com/archi-contribs/database-plugin/files/4984552/DatabasePlugin.log)

**Comment by herve91** [comment]
The SQL request that is failing is "SELECT name, purpose, created_on, properties, features, checksum FROM dbomodels WHERE id = 'id-f1463fee07f547e5b779275d2dd41b4e' AND version = 2"

The dot is missing between "dbo" and "models".

I'll send a fix by the end of the week.

**Comment by herve91** [comment]
fixed in version 2.2.10

Best regards
Hervé
