### ISSUE TITLE
Not able to delete a model

### ISSUE THREAD

**Issue by edvardmokin** [archi-contribs/database-plugin#105]
Get error when delete a model (soft delete). See screen and log attached

**Do we have an option for hard delete ?**

Error due to delete sql statement has dbl quotation for ID instead of single

![image](https://user-images.githubusercontent.com/54371319/90198211-fa2c4d00-dd9e-11ea-9574-b5ebb5020f04.png)

[DatabasePlugin.log](https://github.com/archi-contribs/database-plugin/files/5072024/DatabasePlugin.log)

**Comment by herve91** [comment]
Thanks for reporting this bug.

The fix will be in the next release.

Best regards
Hervé

**Comment by herve91** [comment]
Fixed in version 2.2.12

Best regards
Hervé
