### ISSUE TITLE
documentation: Changelog could not be found

### ISSUE THREAD

**Issue by WatchTh1** [archi-contribs/database-plugin#107]
Dear Herve, could not fint changelogs from v.2.2.7 up to 2.2.12 in wiki, could you provide it pls ? We need to make a decision about updating our environment.

Thanks in advance, Alexander.

**Comment by herve91** [comment]
Hi Alexander,

The complete changelog can be consulted [here](https://github.com/archi-contribs/database-plugin/blob/master/v2/release_note.md).

The changes are mainly related to the admin procedures (accessible through the "admin" button on the database definition spreadsheet in the preference page. These admin procedures include a data check, a database structure check and the ability to delete a model from the models table.

There isn't any database structure change and the import/export procedures haven't been changed between those two plugin versions, so you can safely use both versions 2.2.7 and 2.2.12 on the same database.

Please do not hesitate should you have any other question.

Best regards
Hervé
