### ISSUE TITLE
About Export to Neo4j issue: archimate relationships are transfered as nodes

### ISSUE THREAD

**Issue by devbox2020** [archi-contribs/database-plugin#109]
This is not an issue, rather a clarification:

Thanks for building such a useful plug-in. I appreciate the design feature of using two modes (1) native and (2) extended for archimate relationships. 

What if I used (mode:2) extended relationships to make the most of Archimate's multi-relationship feature and ran a CQL which creates the direct relationship that I am interested in (for analytical purpose), as in the query below:
MATCH (a:elements)-[:relatedTo]->(b:relationships)-[:relatedTo]->(c:elements)
WHERE b.name = "uses"
MERGE (a)-[:uses]->(c);

Question is: will I have trouble importing the model to Archi? Does it, for example, ignore  'user defined' relationships and just import graph elements consistent with Archimate's schema?  Alternatively, Is there perhaps a way to create a View in the db that allows for both to co-exist?

**Comment by herve91** [comment]
Hi,

I'm sorry, I do not understand your question as the plugin can export to Neo4J but not import back. So you can create relationships using CQL but won't be able to import them back to Archi.
