### ISSUE TITLE
For MS SQL - would like to be able to specify schema within database

### ISSUE THREAD

**Issue by GeoffMurray** [archi-contribs/database-plugin#11]
v2.0.2 w/ MS SQL w/Archi 4 Beta 9

MS SQL provided assumes tables will all in the dbo schema. For us, that doesn't work, as we like to group access by schema. I customized the schema generation using the following example. It would be really handy to be able to provide a database and schema reference option in this interface. I worked around it by providing MS SQL synonyms.
[create tables(MS-SQL).txt](https://github.com/archi-contribs/database-plugin/files/974206/create.tables.MS-SQL.txt)

**Comment by herve91** [comment]
Hello,

I do not understand. If you wish to use a specific schema, just assign the user your define in my plugin to this schema.

This (not testes) should work:
CREATE USER archi WITH PASSWORD = '************'
CREATE SCHEMA archi AUTHORIZATION archi
ALTER USER archi WITH DEFAULT_SCHEMA = archi

Best regards
Hervé

**Comment by GeoffMurray** [comment]
It could easily be I don't understand :-) 

Are you creating this user account to be the user account Archi would log in from to export/import from the database?

I was trying to use integrated MS security, so the user management access to the schema would happen there. Since I am using integrated MS security, and we have multiple schema's within the DB, I can't force users to be one or the other. 

I was hoping to be able to specify a schema, so that when the plug in connected to the DB, even in MS Integrated Security, the plugin would know what schema to look in for the tables.

Make more sense?

**Comment by herve91** [comment]
Oh, I understand.

There is no way to indicate a schema name on the JDBC connection string. So at the moment, my plugin is not able to fulfill your requirements.

I will add the possibility to specify a schema name on the preference page.

Best regards
Hervé

**Comment by GeoffMurray** [comment]
Just a thought, but does the JDBC connection string allow you to specify a more fully qualified object name for the table?

Ie, if the table name is "views", but the user provides a schema name of "archi", could you send the JDBC connection request using "archi.views" (for example). In other words, concatenate the schema name with the table name for the final JDBC request to the database?

I've not used JDBC, so I don't know what restrictions it might have.

**Comment by herve91** [comment]
That's exactly what I need to add in my plugin :-)

Best regards
Hervé

**Comment by herve91** [comment]
Hi,

I added the ability to specify a schema in the 2.0.3 version of my plugin.

Best regards
Hervé

**Comment by GeoffMurray** [comment]
Works great! Thanks!
