### ISSUE TITLE
Neo4j registered and yet shows Database error dialog box

### ISSUE THREAD

**Issue by devbox2020** [archi-contribs/database-plugin#110]
This relates to plugin version 2.2.12 (latest) and Archi 4.7.1 Build 202007151058: (latest)

I have registered a neo4j database, checks to see that it connects. 
On the Database plug in > preferences screen (bhaviour mode): When I press the Save button, it reports an error dialog:
Please set up at least one SQL database in Archi preferences. 
It does not recognise the neo4j registration.

However, if I press OK, and open an Archi model, I can use 'export' to successfully export it. 

Unfortunately, When I press 'import' I get the same error again and therefore, I cannot import an neo4j model to archi. 

<img width="748" alt="Screen Shot 2020-10-30 at 8 18 17 PM" src="https://user-images.githubusercontent.com/20623937/97672204-7c9af200-1aee-11eb-89c8-76e95162b8a7.png">

**Comment by herve91** [comment]
The plugin can export to Neo4J but cannot import back from Neo4J

The import process can only deal with SQL databases.
