### ISSUE TITLE
Archi 4.8.0 & NEO4J 2.2.13 DB plugin: NEO4J Export-Settings are not properly saved?

### ISSUE THREAD

**Issue by henrinickels** [archi-contribs/database-plugin#112]
Hello,
I am using Archi 4.8.0 with the Database export plugin version 2.2.13 and I encounter an issue with the NEO4J database type.

In fact, when I select the "Native", "Empty database..." and "Use typed..." options, they are not properly "saved" when the preferences are saved:
![image](https://user-images.githubusercontent.com/76954823/103554000-8a824000-4eae-11eb-8d6c-b714ecacfe2a.png)

When I reopen the preferences, the basic settings selections "Extended", "Leave..." and "Use unique..." options remain selected:
![image](https://user-images.githubusercontent.com/76954823/103554053-9ff76a00-4eae-11eb-9351-8cdc2e32a452.png)

As such, NEO4J does not really contain usable and navigable information and according to the previous thread https://github.com/archi-contribs/database-plugin/issues/94, the NEO4J export settings were already working properly. Any hint about the source/reason for this malfunction and where/how to resolve it?

**Comment by herve91** [comment]
after doing some more testing, it appears that these parameters are effectively not saved when in "expert mode"

I will send a fix in the coming days, but meanwhile, you may switch back in standard mode and those parameters will be saved as expected.

Best regards

**Comment by henrinickels** [comment]
Thanks Hervé. The standard mode option works fine thus there is no urgency on fixing the expert mode.

Merci beaucoup et cordialement,
 Henri

**Comment by herve91** [comment]
The version 2.2.14 has been released and fixes the issue.

Best regards
Hervé

**Comment by henrinickels** [comment]
Dear Hervé,
unfortunately the 2.2.14 version does not resolve the 2.2.13 expert mode issue and especially now even the V2.2.14 standard mode option does not work properly anymore. I had to downgrade from V2.2.14 to 2.2.13 to keep my exports working in standard mode. Thanks  for having a look into that.

**Comment by herve91** [comment]
My bad ... I've been to quick to release this version :-(

Please check version 2.2.15

**Comment by herve91** [comment]
Hi, did you check version 2.2.15 ?

**Comment by henrinickels** [comment]
Dear Hervé,
unfortunately in 2.2.15 the expert mode does save properly.

Here is the screenshots of the saved 2.2.15 Expert config before clicking "Apply" and "Apply and Close":
![image](https://user-images.githubusercontent.com/76954823/104206052-6505b100-542f-11eb-9bcc-e9b7863c1ae2.png)

After clicking "Apply" and "Apply and Close" I closed the Preferences window and I closed Archi.
Following the restart of Archi and the reopening of the Preferences window the following appears:
![image](https://user-images.githubusercontent.com/76954823/104206423-cd549280-542f-11eb-9e4c-96e1f2a60768.png)

In 2.2.15, the standard mode works OK as in 2.2.13.

Best regards,
 Henri

**Comment by herve91** [comment]
Ok, I need to work more on this. I really need to find time to automate my non regression tests as well ...

I'll send a fix in the coming days.

**Comment by henrinickels** [comment]
Dear Hervé, I appreciate your time spent on this but please don't stress, as said the standard mode works fine ;-). Best regards, Henri

**Comment by herve91** [comment]
Hi Henri,

sorry for the long delay, but you said you were not in a rush. I'll send an update tody, if you may confirm it works fine now for you :)

Thanks and regards
Hervé
