### ISSUE TITLE
CommandLine for Export

### ISSUE THREAD

**Issue by michaelansley** [archi-contribs/database-plugin#114]
Hi Hervé,

Not sure if this is the best way to contact you, if not, please point me in a better direction.

Recently we started looking at using the dbplugin for Archi to perform some automated routines, while our daily shared store of models is in Stash using the coArchi plugin.  Based on this, it is necessary to export a model to the database using the dbplugin, yet this is not available on the command line, as far as I can tell.

Is there a reason for this?  Is it something you've tried and struggled with, or it has logical problems, or rather you just haven't had the need?

So far as we've been using it, it is an extremely useful tool!

Regards,
Michael

**Comment by herve91** [comment]
Hi Michael,

This is the right place for this kind of question ...

The database plugin cannot be triggered from the command line as the SQL requests have not been separated from the graphical interface. It tried once to separate them, but it introduced too many issues that I had to rollback.

I keep your case opened as I need to give another try ...

Best regards
Hervé

**Comment by herve91** [comment]
It has been a very long time, but the import and export commandlines have been developped. They will be part of the coming release.

**Comment by michaelansley** [comment]
Awesome!! Thanks very much.
