### ISSUE TITLE
Installation Issue: not treated as Arc

### ISSUE THREAD

**Issue by yasenstar** [archi-contribs/database-plugin#117]
Hello,

Just download and try to install in my Archi 4.8.1, but get error message:

"org.archicontribs.database_2.2.16.archiplugin - Is not an Archi plug-in"

![20210312-archi-db-export-plugin-install-issue](https://user-images.githubusercontent.com/5661654/110950775-42e6bd00-8312-11eb-94e1-f27e7c3b6eb4.png)

Checked your wiki, not sure any more steps I may miss.

Thanks a lot,
Xiaoqi

**Comment by herve91** [comment]
Hi Xiaoqi,

You my have a corrupted file. Please check it is 27 319 415 bytes. I suggest you download it again.

Best regards

**Comment by yasenstar** [comment]
Sorry Herve, thanks for your mentioning, that's indeed my download issue, have re-download, and now the plug-in loaded correctly.

Thanks a lot for the excellent tool, I'll take my time to learn and use that in Archi.

**Comment by herve91** [comment]
You're welcome.

In case on any question, please do not hesitate to ask. I know my documentation needs to be rewritten.

**Comment by yasenstar** [comment]
Thanks a lot Herve.
