### ISSUE TITLE
Getting a database error trying to save a new version of the model

### ISSUE THREAD

**Issue by GeoffMurray** [archi-contribs/database-plugin#12]
v2.0.2 w/ MS SQL w/Archi 4 Beta 9

Managed to export to the database.
Updated the model, and then tried to re-export.

Got an error:

Database import/export plugin v2.0.2
Failed to check existing components in database.

The column name t.version is not valid.

Used schema generated in issue #11

Perhaps I'm misunderstanding, do I just save, or do I re-export?

**Comment by herve91** [comment]
Ok, I believe you've found a bug ...

I'll have a look and let you know ASAP.

Best regards
Hervé

**Comment by herve91** [comment]
Hello,

This issue has been solved in the latest version.

Best regards
Hervé

**Comment by GeoffMurray** [comment]
Works great. Thanks!
