### ISSUE TITLE
elements are not assigned to their correct folders

### ISSUE THREAD

**Issue by moinmoin** [archi-contribs/database-plugin#121]
when importing from model A into a new model B, elements are not assigned into their subfolders.

Example:
* model A has a folder "Appliction/test" with an Application component "AC TEST" in it.
* Application component appears in the root folder of model B.

An analysis of the code points to DBImportElementFromIdCommand Line 116:
115			else {
116				this.newFolder = importConnection.getLastKnownFolder(this.model, "IArchimateElement", this.id);
+				// imported first time into another model
+				if((this.newFolder == null) && (folder != null)) {
+					this.newFolder = folder;
+				}

The last known folder "test" is being selected from model B. The folder "test" doesn't exist there as the import is done into a new model B.  The variable this.newFolder is set correctly IMHO, but has no impact on the result.

**Comment by herve91** [comment]
Hi,

You're not the first to ask this question but I do not have a simple solution.

Basically, when you export a model, they ARE located into a folder. But, those components can be located in several models, and in different folders across those models (thi is a choice made from the beginning).

When you import a component from a database, you do not import this component from one model, you import the component as it is from all the models.

That's the reason why you right click on a folder and then select the "import component from database" from here, the component is imported in that folder (if the imported component is of the right class of course), and when you go in the File / Import menu of Archi and select "import component from database" from here, it is created in the default folder of his class.

I hope this helps.

Happy to discuss this further with you if needed.

Best regards
Hervé

**Comment by moinmoin** [comment]
The problem arises when importing category "models", especially in an empty model.
Again this is interesting in a "force shared mode" when using a global template model in a federated modelling environment.

**Comment by herve91** [comment]
Just released version 4.9.0.beta wich now imports in the correct folder.
