### ISSUE TITLE
features are not imported 

### ISSUE THREAD

**Issue by moinmoin** [archi-contribs/database-plugin#122]
Features (label expressions) are not imported from model A to model B. they can be assigned on ViewElements and Folders.
The database structure is there.

I tried to correct this in the following classes, with execute and undo
DBImportFolderFromIdCommand
DBImportViewObjectFromIdCommand

[Fix-for-import-of-Features-Label-Expressions.txt](https://github.com/archi-contribs/database-plugin/files/6643632/Fix-for-import-of-Features-Label-Expressions.txt)

The result works, but I was not sure of it, so I attached it as a (patch) text-file

**Comment by herve91** [comment]
Hi,

My apologies for the very long delay and thanks a lot for pointing out the bug and providing the solution. It will be part of the coming release that will also fix few other bugs.

Best regards
Hervé
