### ISSUE TITLE
ORA-00932 on Import

### ISSUE THREAD

**Issue by Stefaney-MP** [archi-contribs/database-plugin#124]
I'm receving an Oracle-Error on Import:
![image](https://user-images.githubusercontent.com/90898816/133752952-7dba2976-8b92-4492-a8d0-af967072f67e.png)

Export works just fine; the Log-Files shows an error:
[DatabasePlugin.log](https://github.com/archi-contribs/database-plugin/files/7184126/DatabasePlugin.log)

As I'm a newbie: what am i doing wrong?

**Comment by herve91** [comment]
ORA-00932 is a datatype issue. The error message seems to indicate that the expected CLOB column has been transformed to another datatype that cannot be converted to a CLOB by Oracle.

Did you a manual operation on the database ?

You may try to go to the preferences page, select your database and click on the "admin button" and then select the "check structure" action. You then may have more details on the database errors but the plugin won't be able to fix it by itself.

**Comment by Stefaney-MP** [comment]
No, i didn't alter any of the tables; check structure doesn't reveal any problems:

![image](https://user-images.githubusercontent.com/90898816/134121808-0ea16326-34e1-4605-a7b5-2861372d584f.png)

The database-structure (affected tables) seems ok to me - if i interpret the log-File correctly:
![image](https://user-images.githubusercontent.com/90898816/134122654-eddb4dfa-7073-4616-bd2d-c4044aa42d3d.png)

Is it possible, that there is a problem with our DB-Version 19c?

**Comment by Stefaney-MP** [comment]
We analyzed the problem further; it seems, there is a problem with one Column (strength). The original statement as indicated in the log leads to an error:

```
SELECT COUNT(*) AS countRelationships 
  FROM (SELECT DISTINCT relationship_id, 
                        parent_folder_id, 
                        version, 
                        class, 
                        name, 
                        TO_CHAR(documentation) AS documentation, 
                        source_id, 
                        target_id, 
                        strength, 
                        access_type, 
                        is_directed, 
                        created_on, 
                        properties, 
                        features, 
                        checksum 
            FROM ARCHI.relationships_in_model 
      INNER JOIN ARCHI.relationships ON id = relationship_id AND version = relationship_version WHERE model_id = 'our_model_id' AND model_version = 1
      GROUP BY relationship_id, 
               parent_folder_id, 
               version, 
               class, 
               name, 
               TO_CHAR(documentation), 
               source_id, 
               target_id, 
               strength, 
               access_type, 
               is_directed, 
               properties, 
               features, 
               created_on, 
               checksum
      ) relts
=> ORA-00932: inconsistent datatypes: expected - got CLOB
```
If i alter the SELECT-Statement a little bit - similar to column documentation - the statement works:

```
SELECT COUNT(*) AS countRelationships 
  FROM (SELECT DISTINCT relationship_id, 
                        parent_folder_id, 
                        version, 
                        class, 
                        name, 
                        TO_CHAR(documentation) AS documentation, 
                        source_id, 
                        target_id, 
                        TO_CHAR(strength) AS strength, 
                        access_type, 
                        is_directed, 
                        created_on, 
                        properties, 
                        features, 
                        checksum 
            FROM ARCHI.relationships_in_model 
      INNER JOIN ARCHI.relationships ON id = relationship_id AND version = relationship_version WHERE model_id = 'our_model_id' AND model_version = 1
      GROUP BY relationship_id, 
               parent_folder_id, 
               version, 
               class, 
               name, 
               TO_CHAR(documentation), 
               source_id, 
               target_id, 
               TO_CHAR(strength), 
               access_type, 
               is_directed, 
               properties, 
               features, 
               created_on, 
               checksum
      ) relts
=> works just fine
```

**Comment by Stefaney-MP** [comment]
According to Oracle19c-Docu this is to be expected:

Database SecureFiles and Large Objects Developer's Guide

•	You cannot specify LOB columns in the ORDER BY clause of a query, the GROUP BY clause of a query, or an aggregate function.

Workaround = mask with TO_CHAR

In our Setup LOB's are stored as SecureFiles, which is recommended by Oracle.

**Comment by herve91** [comment]
Thanks a lot for your analyse. It might be specific to Oracle 19c because I never experienced this issue on My Oracle 12c database.

Whatever, I'll fix all my SQL requests according to your solution. I'm confident I'll be able to send the fix today.

**Comment by Stefaney-MP** [comment]
Thank your for your fast response - and the fix! Right now it's no pressing issue,  so take your time :-)

**Comment by herve91** [comment]
I just released the version 2.2.21 that fixes the strength clob access. I did regression testing on my database but did not have time to instantiate an Oracle 19c to conduct tests on this specific version.

Please do not hesitate to tell me if this new version does not solve your error.

**Comment by Stefaney-MP** [comment]
Thank you very much for the quick fix - works like a charm!

**Comment by herve91** [comment]
Great. Happy it works.

I close your issue.
