### ISSUE TITLE
[enhancement] Support Archi 4.9

### ISSUE THREAD

**Issue by davidsara** [archi-contribs/database-plugin#129]
Hello!
Thanks for the great plugin!
Are there plans for 4.9 support? Now I cannot select my database (created in 4.8) which I guess is for the purpose as data model will be extended for the new Specialization feature.

Thank you, David

**Comment by herve91** [comment]
Hello,
An alpha version is available. You can access it by selecting the Archi_4.9 branch.
Please do not hesitate to open an issue if you discover misbehaviors.

![image](https://user-images.githubusercontent.com/9281982/137267955-082b870a-289b-4f0d-aabc-4bc61506791b.png)
