### ISSUE TITLE
How can we use the screenshot data associated with the views table?

### ISSUE THREAD

**Issue by GeoffMurray** [archi-contribs/database-plugin#13]
v2.0.2 w/ MS SQL w/Archi 4 Beta 9

Is there a render engine that can input what appears to be binary data and produce an image?

**Comment by herve91** [comment]
The views images have been required by people who wanted to print it in a web site. I did not ask them how they would get the data, but I suppose PHP would do it (not tested)

$sql = "SELECT screenshot FROM views WHERE id = 'xxxxx' AND version = xxx;";

$result = sqlsrv_query($conn, $sql) or die(sqlsrv_errors());  
$row = sqlsrv_fetch_array($result, SQLSRV_FETCH_BLOB);

header("Content-type: image/png");
echo $row['screenshot'];

Best regards
Hervé

**Comment by GeoffMurray** [comment]
Ok - thanks. That was enough of a clue to get me going. Awesome!

**Comment by GeoffMurray** [comment]
I just queried the views table, and wrote out a binary file:
- name was view 'id' + .png. 
- contents was the 'screenshot' field.

Opens beautifully.

**Comment by herve91** [comment]
Great.

Thanks for the update
Hervé
