### ISSUE TITLE
4.9alpha import exception

### ISSUE THREAD

**Issue by davidsara** [archi-contribs/database-plugin#130]
Import is done from 4.8.1 database after structure upgrade performed by 4.9 alpha plugin.

SqlServerException during the import:
![image](https://user-images.githubusercontent.com/20066733/137309798-c759fe7d-205a-4b87-b513-fa46bea275c6.png)

Check structure:
![image](https://user-images.githubusercontent.com/20066733/137309860-663826a2-1df0-4c7e-8103-374652b99fa0.png)

**Comment by tumesh** [comment]
![image](https://user-images.githubusercontent.com/18109627/140088204-50ccebca-45ad-40c4-a6a6-db1a2ee586e8.png)
Is this a known issue ? database plugin v2.2.19 in Achimate 2.9.1 ?
![image](https://user-images.githubusercontent.com/18109627/140088329-b9203b27-a7e0-4aa2-8f07-3c576fce1933.png)

**Comment by tumesh** [comment]
And it looks like UI formatting went cranky too.. any idea about the fix for this problem ?
![image](https://user-images.githubusercontent.com/18109627/140089218-559e3668-3f18-4247-af4a-087d828fab89.png)

**Comment by herve91** [comment]
@tumesh
re the nullPointer Exception, please open a new issue with the exception found in the log file 
re the Gui, it is effectively the case on HiDPI displays. I'm already working on it

**Comment by tumesh** [comment]
> @tumesh re the nullPointer Exception, please open a new issue with the exception found in the log file re the Gui, it is effectively the case on HiDPI displays. I'm already working on it

I wonder where can I find log files ? I couldn't find any settings to set logging file nor in Archimate application folders including Users folder in App Data. btw I am using Archimate in Win7. 

Thank you very much! 

I am really interested in working on this project more actively.

**Comment by herve91** [comment]
you must enable log file in the logger tab of the plugin preferences page, and select trace 
![image](https://user-images.githubusercontent.com/9281982/48304723-76d12e00-e51e-11e8-8149-6327b6aec343.png)

**Comment by herve91** [comment]
Just release the version 4.9.0.beta.

could you please check ?

**Comment by davidsara** [comment]
I can confirm beta version is working. Thank you!
