### ISSUE TITLE
Archi 4.9 and DataBase export plugin

### ISSUE THREAD

**Issue by sportingdurutti** [archi-contribs/database-plugin#131]
Version of Archi
4.9

Archi Plug-ins
org.archicontribs.database_2.2.19
org.archicontribs.modelrepository_0.7.1.202102021056

Operating System
Windows 11

Expected Behaviour
Test connection ok. Save and start exporting

Actual Behaviour
Database export plugging giver error while initializing. Test Connection is ok when closing windows give null reference

Steps to Reproduce the Behaviour
Choose an existing connection (eg: neo4j)
Save
Select connection and stat exporting

**Comment by herve91** [comment]
Hello,
An alpha version is available. You can access it by selecting the Archi_4.9 branch.
Please do not hesitate to open an issue if you discover misbehaviors.

see #129
