### ISSUE TITLE
NullPointerException after Import

### ISSUE THREAD

**Issue by Stefaney-MP** [archi-contribs/database-plugin#134]
I'm very sorry to bother you again (you must hate me by now), but I'm experiencing another issue: After Importing the Model I cannot change properties. If the component already has properties, the value-field cannot be edited (neither for new properties nor existing ones). If the component has no properties, a null point exception occurs:

![image](https://user-images.githubusercontent.com/90898816/143252556-4daf864a-fc8a-402c-a50b-432462813948.png)

As far as i can tell the DB-Log shows nothing suspicious (Log-Level TRACE): 

[DatabasePlugin.log](https://github.com/archi-contribs/database-plugin/files/7596250/DatabasePlugin.log)

The problem can be reproduced using the model I sent you on Monday.

**Comment by herve91** [comment]
Hi, Please be sure that you do not bother me :)

I can't work on this this weekend, but I'll have a look early next  week. I'll let you know asap.

**Comment by herve91** [comment]
Hi Stefaney,

It's been quite tough but I finaly understood what happens ...

If you edit your archimate file (it's in XML format), you'll find elements with and without properties ... and some empty property sections:
`<property/>`

As a consequence, when you load your Archimate file, Archi creates a "null" property and shows up this null property using the "(blank)" keyword in the name column and an empty string in the value colomn:
<img width="329" alt="image" src="https://user-images.githubusercontent.com/9281982/144318981-99495d2e-4e5b-4c28-8941-bac6fa687dd5.png">

Unfortunately, as this situation should not happen, I do not trap the null properties and create in the database a property with a null name and an null value. So when you import your model back from the database, Archi gets a real property with null content which triggers a nullPointerException when you access it.

I'll update my plugin to stop exporting (and importing back) such null properties.

**Comment by herve91** [comment]
Please try version 4.9.2 that I just released.

I let you check and close the issue if you validate the fix.

ps: please do not keep the plugin log file in TRACE mode as it has got an impact on the plugin performances. So you may come back to INFO mode or even switch it off.

**Comment by Stefaney-MP** [comment]
Hi,

thank you for the new version, which fixed the export/import-problems with our model. But when trying to export a changed model back to the DB, we now receive a new error:

![image](https://user-images.githubusercontent.com/90898816/144588825-863e78c0-21d1-48ce-8369-610495a6309f.png)

Trace-File:
[DatabasePlugin.log](https://github.com/archi-contribs/database-plugin/files/7648794/DatabasePlugin.log)

**Comment by Stefaney-MP** [comment]
After initializing the DB as suggested everything works as expected - thanks for the new version!
