### ISSUE TITLE
Components not imported back in correct sub-folder when located two levels or more under root folder

### ISSUE THREAD

**Issue by JeanPierre32** [archi-contribs/database-plugin#135]
Hi Hervé,

First of all I would like to thank you for the great job you're doing on database-plugin. The database-plugin is enabling us to federate candidate architecture models and sharing baseline and target EA components across models.

Here we need to have components located in a sub-folder hierarchy (two levels or more) under each root folder.
When we export the model to database and then import it back into a new empty model, components located  at level two or more are imported back at root level.

For example if "My Shared Application Component" is located in subfolder level 1:

![image](https://user-images.githubusercontent.com/95302473/144088521-f43ccbd8-be24-4e8c-bacd-8abfa656b7c9.png)
![image](https://user-images.githubusercontent.com/95302473/144089378-a6cad000-7cda-4498-8fb5-81b3da0b78cc.png)

then, it is imported back in a new model at the same place and it's OK:

![image](https://user-images.githubusercontent.com/95302473/144090512-f0f25140-8e41-4239-a9bb-91adbb20ce2b.png)

But if located in subfolder at level 2:

![image](https://user-images.githubusercontent.com/95302473/144091469-ab83ed2c-6ce4-4d59-b40c-38f086a3f8c1.png)

then it is imported back at root "Application" level:

![image](https://user-images.githubusercontent.com/95302473/144091574-45387db7-1905-4f55-94c8-3794464d591e.png)

Regards,

Jean-Pierre

**Comment by herve91** [comment]
Hi Jean Pierre,

I'll do some testing and come back to you asap.

**Comment by herve91** [comment]
Hi Jean-Pierre,

I conducted more testing and failed to reproduce your issue. Here is what I did:

test 1:
- load model from Archimate file
- export it to an empty database
- close model
- import model back from database

test 2:
- load model from Archimate file
- export it to an empty database
- close model
- create a new empty model
- select "import components from database" in Archi menu and merge model in template mode

in both cases, my components are in the correct folder aven at level two:
![image](https://user-images.githubusercontent.com/9281982/144206528-aaeb5225-85d2-43ca-8fc7-91e1049a7b4c.png)

**Comment by JeanPierre32** [comment]
Hi Hervé,

I tested again after creating an empty database to be as close as possible to your test case.
[sample-project.zip](https://github.com/archi-contribs/database-plugin/files/7633020/sample-project.zip)

**TEST2 => same results as you:**

![image](https://user-images.githubusercontent.com/95302473/144213320-174e1054-5fab-46cb-a037-7ca055949c69.png)

![image](https://user-images.githubusercontent.com/95302473/144213881-95c79a4a-dda6-488f-ba99-d7b839930abe.png)

![image](https://user-images.githubusercontent.com/95302473/144214175-a9c92c38-a27f-4c53-aefb-5eb2144ccd82.png)

![image](https://user-images.githubusercontent.com/95302473/144214469-88970b1a-74fd-423d-8842-16fffa80251a.png)

![image](https://user-images.githubusercontent.com/95302473/144214638-77a8ddca-1627-475c-9c0d-3d9f2e3f6a23.png)



**TEST 2 => component not merged in the correct folder:**

![image](https://user-images.githubusercontent.com/95302473/144215160-4971fc7c-e200-43c5-9dc2-53b72ed64163.png)

![image](https://user-images.githubusercontent.com/95302473/144215440-7bdc4e7f-387a-4432-bd02-95c5101b9e9c.png)

![image](https://user-images.githubusercontent.com/95302473/144215664-f532e039-5074-4dd6-a8aa-aa695e55dae8.png)



It's weird, perhaps we don't have the same versions of components ?
![image](https://user-images.githubusercontent.com/95302473/144218991-9e6042c9-39f5-4c12-8be7-279617bc7803.png)

**Comment by herve91** [comment]
Just to be sure, could you please provide me which database brand and version you're using that I conduct tests with same database engine ...

**Comment by herve91** [comment]
I downloaded your sample model and did:
- Open your sample model from Archimate file
- Export model to the database
- Close model
- Import model back from the database
And the component is located in its correct folder:

![image](https://user-images.githubusercontent.com/9281982/144227216-88e3b843-23e6-4876-a726-448d534f355b.png)


Could you please summarize instructions to reproduce your issue ?

**Comment by herve91** [comment]
I finally succeeded to reproduce your issue :)

I'll send a fix asap.

**Comment by JeanPierre32** [comment]
Good news !
To answer your previous question: I'm using MS SQL SERVER 15.0.2000 (EXPRESS)

**Comment by herve91** [comment]
Fix in version 4.9.1 just released but to be honnest, I'm not really happy with my code so sooner or later, I'll have ro rewrite all this part.

Anyway, It works better now. I let you check and close this case if you're happy with the fix.

**Comment by JeanPierre32** [comment]
Just finished to check, the fix is OK :-)

Thanks again
