### ISSUE TITLE
Wrong 'Created on' date for folders

### ISSUE THREAD

**Issue by vbo75** [archi-contribs/database-plugin#137]
Hi,

'Created on' date isn't correctly update for folder element.

![image](https://user-images.githubusercontent.com/60790536/145236059-0cd0d036-f83e-453b-8c47-16de28ee451b.png)

**Comment by herve91** [comment]
Hi Vincent,

Thanks for raising this issue. I'll have a look and let you know ASAP.

**Comment by herve91** [comment]
The date was not exported correctly in the database, thus wrong everywhere.

Will be fixed in version 4.9.3 that will be released soon.
