### ISSUE TITLE
Wrong 'Created by' in History 

### ISSUE THREAD

**Issue by vbo75** [archi-contribs/database-plugin#138]
Hi,

On the history window, the 'Created by' of the 'Your version' colon is not correctly display. It display the local user instead of user in the database version.

In this exemple, the local version is the version number 6 created by xdkc031, so I should have the same name in the 'Your version' colon.

![image](https://user-images.githubusercontent.com/60790536/145237798-5c86e0e3-4f5c-40e9-97b4-fefdf874d3eb.png)

**Comment by herve91** [comment]
Hi Vincent,

Thanks for raising this issue. I'll have a look and let you know ASAP.

**Comment by vbo75** [comment]
Hi Hervé,

Yes, that's what I was expecting.
If the current object version is the same has one's in the database, it must be the same information on both column, else it's a "new" version created by the current user. In that way, maybe It could be more understandable to print "based on (# version)" in the version/Your version cell.

**Comment by herve91** [comment]
Great, so the fix will be part of the 4.9.3 version that will be released soon
