### ISSUE TITLE
Export/Import buttons desabled on the History window

### ISSUE THREAD

**Issue by vbo75** [archi-contribs/database-plugin#139]
Hi,

When I select a previous version of an item, both export and import buttons are still desabled.

![image](https://user-images.githubusercontent.com/60790536/145238844-af619708-cc1f-457b-bf4e-23412d3f2e2d.png)

**Comment by herve91** [comment]
Hi Vincent,

Thanks for raising this issue. I'll have a look and let you know ASAP.

**Comment by herve91** [comment]
Hi Vincent,

As seen with you by mail, the Import / export buttons are automatically enabled and disabled depending on the comparidon between the local and the database versions.

I close this issue.
