### ISSUE TITLE
Need to create an export version of a model even if just need to pull the latest version of the database

### ISSUE THREAD

**Issue by vbo75** [archi-contribs/database-plugin#140]
HI,

When you are at the model level, you need to create an export version even if you just want to get the latest version of the model in the database.
Is it possible to have a 'get history' function at the model level ?

**Comment by herve91** [comment]
Hi Vincent,

I don't understand what you mean. Could you please explain a bit more ?

**Comment by vbo75** [comment]
Hi Hervé,

When you right-clic on a element or view in the model, you have the "Get History..." function. In that case, you can directly get a new version of that element if it was updated by someone else on the database.
But when you right-clic on the model, there isn't that "Get History..." function. So if you just want to update the whole model with a new one that was droped in the database, you need to "Export" first your current model on the database, and after your current model is updated with the lastest version. In that case, there was a not expected version created in the database.

In the same time, if the current model has changes, they must be check by the function and ask for user if he wants to keep those changes (and so on create a new version on the database) or to overwrite the current model.

**Comment by herve91** [comment]
Ok, thanks for those precisions. Will be part of the version 4.9.3 that will be release soon.

**Comment by herve91** [comment]
Hi,

Getting history from a model has been added but forcing the model information update without going through the "export model" function is too complex to implement as it would impact a lot the conflicts detection and resolution mechanism.

Should you need to update the model information to the database, please go through the "export model" function.
