### ISSUE TITLE
Browse button doesn't work

### ISSUE THREAD

**Issue by vbo75** [archi-contribs/database-plugin#142]
Hi Hervé,

When I try to set log file name in Logger tab, "Browse..." button doesn't work, no file's explorer window is shown.

![image](https://user-images.githubusercontent.com/60790536/145790913-bc2a5029-237c-48c8-b708-4b8ca0df435a.png)

**Comment by herve91** [comment]
Hi Vincent,

I've got the same issue on my desktop, which is strange because it is a SWT component and I did not change the way I call it. I'll try to update my Eclipse spftware to check if it updates the corresponding SWT component and solves this issue.

I'll let you know.

**Comment by herve91** [comment]
Found the issue. Will be fixed in next release.
