### ISSUE TITLE
Import/open from repository in v4.9.2 Does not working

### ISSUE THREAD

**Issue by michalradacz** [archi-contribs/database-plugin#143]
Big problem. After update to version 4.9.2 from 4.8.2 and success updating SQLITE repositories, on importing it halts on 2 percent of importing and nothing else does. :-( It means we cannot open any repository from DB. 

Tested on multiple repositories and on multiple machines, same result. Repo DBs are okay, because releasing previous versions of DBs and downgrading plugin to older version 4.8.x works fine.

There are no additional informations, log looks that plugin starts importing elements, then relationships and then NOTHING happens. After manually closing import dialog, elements and relationships visible in model, but no views etc.

**Comment by herve91** [comment]
Plugin version 4.9.x is planned to work with Archi 4.9. are you using Archi 4.9 ?

If yes, could you please go to plugin preferences, logger tab and then activate the log file in trace mode.

I need the end of your log file with the lines corresponding to when the plugin stops responding.

**Comment by herve91** [comment]
Could you please provide me the error found in the log file, without the error message, I cannot investigate ...

**Comment by herve91** [comment]
Sorry, but without more information, I cannot investigate.

Please reopen this case when you've got more inforamtion to provide me.
