### ISSUE TITLE
Import filter - components (un/selecting corresponding classes)

### ISSUE THREAD

**Issue by edu-skill-bill** [archi-contribs/database-plugin#145]
Hi Herve,
might be possible (in new version of plugin 4.9.4) to align set of components with ArchiMate 3.1 standard? I found that "Value Stream" is missing. I tested the functionality, whether this element will not be included when selecting the import of the whole layer (Strategy), but not.
Thank you. Lubos

**Comment by herve91** [comment]
Good morning Lubos,

The value stream is effectively missing from the "import components from database" window. It will be fixed in the next release.

Thanks for pointing out this issue.

Best regards
Hervé

**Comment by herve91** [comment]
Hi Lubos,

I just released the version 9.2.4 that fixes your issue.
