### ISSUE TITLE
Importing canvas throws NullPointerException

### ISSUE THREAD

**Issue by Re4son** [archi-contribs/database-plugin#148]
Love your work!

There is an issue when importing a canvas view, resulting in a NullPointer exception.

Steps to reproduce:

1. Create model
2. Add `Blank Canvas` under `Views`
3. Export model to database
4. Close model
5. Create new model
6. Import components from database
7. Select previous model that contains canvas
8. `Import`
9. Error message:

    ```
    Couldn't import component.

    NullPointerException
    ```

Importing the model from database works fine. It's only when importing components into an existing model.

Hope that helps

**Comment by herve91** [comment]
Hello,

I succedded to reproduce the issue. I'll send a fix soon.

Best regards
Hervé

**Comment by herve91** [comment]
Fix will be part of next release.

Thanks for raising this issue.

Best regards
Hervé
