### ISSUE TITLE
import doesn't handle folders

### ISSUE THREAD

**Issue by peterprib** [archi-contribs/database-plugin#15]
The database seems to record the information but there appears to be no way of importing the structure

**Comment by herve91** [comment]
Hi Peter,

I do not understand what you mean. Could you please provide me with more information ?

Best regards
Hervé

**Comment by peterprib** [comment]
When a sub folder is create and a object moved to this sub folder, this information appears to be exported but there appears to be no means of importing such folder and nor are the sub folder created when an object imported.

**Comment by herve91** [comment]
I understand what you mean.

At the beguinning, I was importing the folder structure at the same time as I import the elements.

Unfortunately, doing this conducted to an unwanted side effect:
if the element was moved to another folder in one model, then it would disapear from all the other models.

So, at the moment, when you import elements, they are imported in their default folder and can be moved to any folder without impacting the other models.

Best regards
Hervé

**Comment by peterprib** [comment]
Surely if the folders are model dependent, and you allowed the object to be contained in more than one model folder this should overcome this issue.  If the import allowed folder structures to be imported with option move of existing this would greatly enhance the offering.

**Comment by herve91** [comment]
Hi,

I still do not have a clean solution to share folders between models.

What I can suggest is that you create dedicated view for this purpose and share these views across models. I fully understand that this is just a caveat but do not have other solution.

Best regards
Hervé
