### ISSUE TITLE
Error on importing models with specializations sharing same image

### ISSUE THREAD

**Issue by Re4son** [archi-contribs/database-plugin#150]
Tested with MySQL.
Importing a model with specializations that share an image throws the following error:

```
No error has been raised during the import process,
but the count of imported components is not correct !
```
Steps to reproduce:

1. Create new model
2. Add 2 specializations, I used principles
3. Add two objects to model, I used principles, and make them a specialization each of the ones you created
4. Export to database, all ok
5. Add the same image to each specialization
6. Export to database
7. Close model
8. Import model from database
9. Error

**Comment by Re4son** [comment]
Looks like all boolean columns are created as smallint using the postgresql driver

**Comment by Re4son** [comment]
Changing column type "BOOLEAN" to "BOOL" fixes that problem but requires "is_locked" & "is_directed" to be changed to a newly created type "TINYINT".

I'd prefer changing the is_specialization queries to work with type smallint instead.

**Comment by herve91** [comment]
Fix will be part of next release.

Thanks for raising this issue.

Best regards
Hervé
