### ISSUE TITLE
Database Plug-in 4.9.5 Installation Issue

### ISSUE THREAD

**Issue by yasenstar** [archi-contribs/database-plugin#152]
Hi Herve,

See you've released Database Plug-in 4.9.5, I'm using 4.9.3 now which is OK, however, when installing 4.9.5 I got below "invalid distance code" error.

Regards,
Xiaoq
![TinyTake24-07-2022-09-44-35](https://user-images.githubusercontent.com/5661654/180850231-6313a6d5-5b6a-45d8-a446-b5d8f14091cb.png)
i

**Comment by herve91** [comment]
Hi Xiaoq,

I just uninstalled my plugin, download back the plugin from GitHub and re-installed it and I experienced no issue on my side.

Could you please verify that the file you downloaded is correct ? It should be 28 811 804 bytes in size. If not, please re-download it.

I believe it's time for me to add a signature file to help validate the downloads ;)

Please keep me informed
Best regards
Hervé

**Comment by herve91** [comment]
closed as no answer
