### ISSUE TITLE
Nested folders not recognised when importing certain components from db

### ISSUE THREAD

**Issue by Re4son** [archi-contribs/database-plugin#153]
Some components are not imported into the correct folder when the following conditions exist:

- Folder structure is deeper than top level folder + 1
- Importing components from db into model imported from db
- Certain objects only, e.g. Value Stream, Application Component, Data Object, Constraint, etc.

These object are imported under the folder "top level folder + 1" and not deeper

Steps to reproduce:

1. Create new model and export to database
2. Export [attached example model containing nested folder structure](https://github.com/archi-contribs/database-plugin/files/9205641/Debugging.zip) into database
3. Close all models in archi
4. Import new model from step 1
5. Import components from db into model and choose the model from step 2

Result: Various object have been moved up from Folder11 to Folder1

Tested with various versions of Archi, various databases, & latest version of db plugin,

**Comment by herve91** [comment]
Hi,

Unfortunately, the begaviour you describe is not a bug but the way I developped the plugin. 

Basically, components can be linked to several models, each of them having their own folders structure. The case you describe with two models only is quite a simple case, but when the database contains dozens or hundreds of models having linked components in different folders, if becomes impossible to know in witch folder to import it.

That's the reason why I import components in their default folder.

**Comment by Re4son** [comment]
I appreciate that behavior when importing selected components but this is not what happens when you import entire models.
The entire folder structure is created and:
- some of the objects are placed in the correct folders
- some are place one folder beneath the default folder
- none are place in the default folder

**Comment by herve91** [comment]
Yes, you're right. It needs improvement.

I'll work on it and let you know as soon it's done.

**Comment by Re4son** [comment]
You're an absolute legend! Thanks heaps.

**Comment by herve91** [comment]
My apologies, I do not have a lot of time at the moment.
Just to keep you informed, I fixed it when importing elements and still need to fix it when importing relationships.

**Comment by Ellers01** [comment]
Would like to add I'm also having this issue atm. Keen for any updates 👍

**Comment by herve91** [comment]
Hi,
I just posted new version 4.9.6 which fixes your issue.
