### ISSUE TITLE
Archi->neo4j Export/Import Error

### ISSUE THREAD

**Issue by TBryanB** [archi-contribs/database-plugin#154]
I keep getting the error message "ParameterIndex does not correspond to a parameter marker in the SQL statement".  I can import an Archi architecture with a handful of entities into neo4j, but when I try to import the whole architecture, I keep getting this error message.  Any idea what's going on?

**Comment by TBryanB** [comment]
Running Windows 10, Archi database plugin 4.9.5, neo4j 4.4.10

**Comment by TBryanB** [comment]
and Archi version 4.9.2

**Comment by TBryanB** [comment]
Just noticed one other thing.  The beginning of the error message says "Failed to empty the Neo 4j database"

**Comment by TBryanB** [comment]
also, the message leads off by saying "Failed to export the model to the database"

**Comment by TBryanB** [comment]
![Error](https://user-images.githubusercontent.com/112726720/188650454-6dd940e0-d26e-4844-8be6-0ec9effe5b46.PNG)

**Comment by TBryanB** [comment]
FYI - I noticed while troubleshooting that I trigger this error message when I put a Specialization on a element or relationship in my Archi model.  Doesn't seem to like Specializations.

**Comment by TBryanB** [comment]
FYI - I noticed while troubleshooting that I trigger this error message when I put a Specialization on a element or relationship in my Archi model. I deleted all the Specializations in the model and was able to successfully export/import the model from Archi to neo4j.  That appears to have been the issue.

**Comment by herve91** [comment]
Hi,
I just posted new version 4.9.6 which fixes your issue.
