### ISSUE TITLE
Changing Element Specialization after Creation does not trigger update to database

### ISSUE THREAD

**Issue by StickeyTape** [archi-contribs/database-plugin#155]
When you have an existing element in the model and change its specialization from its current to a different value, it does not get flagged as a change that is picked up by the plugin when doing an export model to database.

This results in the database and the .archimate file having different specialization for the object.

Steps to Reproduce:

1. Create New Object - leave specialization as (none)
2. Export to Database - inserts the element into DB
3. Create New Specialization 
4. Export to Database - inserts the specialization into DB
5. Change Object Specialization - change from (none) to New Specialization
6. Export to Database - The plugin confirms DB is in sync with model and no changes required.  [this is wrong - the changed specialization should be seen as a change in the model that needs to go to the database during the export.]

Archimate Version 4.9.3
Database Plugin Version 4.9.5
Database Version MySQL 8.0.30

**Comment by herve91** [comment]
Hi,

My apologies for this late answer, I haven't been available these last days. 

I succeeded to reproduce your issue. The fix will be included in the next release.

**Comment by herve91** [comment]
Hi,
I just posted new version 4.9.6 which fixes your issue.

**Comment by StickeyTape** [comment]
Thanks. Can confirm after the update to 4.9.6 that the module does detect Specialization changes and flags them for population to the database model.
