### ISSUE TITLE
Bunded SQL JDBC driver version mismatch

### ISSUE THREAD

**Issue by danielwagn3r** [archi-contribs/database-plugin#157]
The bundled SQL JDBC auth dll has a version mismatch with the updated SQL JDBC driver.

**Comment by herve91** [comment]
There is no auth dll file bundled in the plugin. You must install it manually.

You may download it from Microsoft or download it from the "MS SQL sqljdbc_auth.dll" folder that I just updated.

**Comment by danielwagn3r** [comment]
@herve91 I meant this https://github.com/archi-contribs/database-plugin/tree/master/v2/MS%20SQL%20sqljdbc_auth.dll but the newer dll has been added a few minutes ago.
