### ISSUE TITLE
Neo4j export - AuraDB instance

### ISSUE THREAD

**Issue by seremana** [archi-contribs/database-plugin#159]
thanks for the great work on this plugin so far!

I would like to test the export capabilities to graph in neo4j.  This on a (free) managed instance, AuraDB.

Could it be that the neo4j driver used does not allow connection using the connectionstring template below? 
jdbc:neo4j:neo4j+s://{host}[:{port}]/

For reference, below is a similar configuration in a DBeaver client
https://aura.support.neo4j.com/hc/en-us/articles/6507201423635-How-to-connect-to-AuraDB-instance-using-DBeaver-

It would be great if this neo4j variation was also supported from the plugin!

thx

**Comment by herve91** [comment]
Hello,
When you configure a database, you can switch to expert mode where you can manually edit the JDBC connection string. As AuraDB does support Cypher language, I suppose it would work, but I didn't test.

**Comment by herve91** [comment]
Hello,
did you try the expert mode ? did it answer your question ?

**Comment by egrandry** [comment]
Hello 
I have the same issue: I can't connect to my AuraDB instance. I tried the expert mode and specified the jdbc connect string with the neo4j+s protocol, but without success. Is neo4j+s protocol supported ? 
java.sql.SQLException: org.neo4j.driver.exceptions.ServiceUnavailableException: Failed to discover an available server
org.neo4j.driver.exceptions.ServiceUnavailableException: Failed to discover an available server
  org.neo4j.jdbc.bolt.impl.BoltNeo4jDriverImpl.connect(BoltNeo4jDriverImpl.java:104)
 
When switching to bolt protocol 
java.sql.SQLException: org.neo4j.driver.exceptions.ServiceUnavailableException: Connection to the database terminated. Please ensure that your database is listening on the correct host and port and that you have compatible encryption settings both on Neo4j server and driver. Note that the default encryption setting has changed in Neo4j 4.0.

Any idea what the problem could be ? 

Best

**Comment by herve91** [comment]
Hi,

As stated, I tested the plugin with an on-prem Neo4J instance (currently in version 5.1.0). I never tried with a cloud instance (AuraDB). 

Per my understanding, the JDBC driver of Neo4J does not work with auraDB instances because of encryption issues.

**Comment by herve91** [comment]
Newer version of the Neo4J JDBC driver implements the protocol "bolt+s" that is implemented by AuraDB.

I updated the driver and will add a SSL flag to accomodate AuraDB. It will be included in the coming release.
