### ISSUE TITLE
Import individual component in view

### ISSUE THREAD

**Issue by ZinovyevMaxim** [archi-contribs/database-plugin#16]
Hi!

Herve in the "import individual component into view" window in the context menu of the display if there are two components with the same name it is not clear who is who, you can display the next field of documentation?

**Comment by herve91** [comment]
Hi,

No pb. I let you know as soon this is done.

Best regards.

**Comment by herve91** [comment]
Hi Maxim,

I added the documentation field in the "import individual component" table. It will be available in the next plugin release (hopefully before the end of the month).

Best regards
Hervé
