### ISSUE TITLE
Archi Specialization Field Not Showing Up In Neo4j

### ISSUE THREAD

**Issue by TBryanB** [archi-contribs/database-plugin#161]
When I select a Specialization for an object within Archi, it doesn't seem to be showing up in Neo4j with the other node's meta-data.  Should I be looking somewhere else?  Thank you for your assistance.
![PluginIssue](https://user-images.githubusercontent.com/112726720/217089020-4fd9537c-b40e-4384-bed4-508945f9f8a8.JPG)

**Comment by herve91** [comment]
I did not have the usage so the specialization is not exported in Neo4J databases. I'll add it to the next release.

**Comment by TBryanB** [comment]
Ok, thanks for the notice. Sent from my Galaxy
-------- Original message --------From: Hervé Jouin ***@***.***> Date: 2/6/23  4:28 PM  (GMT-05:00) To: archi-contribs/database-plugin ***@***.***> Cc: TBryanB ***@***.***>, Author ***@***.***> Subject: Re: [archi-contribs/database-plugin] Archi Specialization Field Not
  Showing Up In Neo4j (Issue #161) 
I did not have the usage so the specialization is not exported in Neo4J databases. I'll add it to the next release.

**Comment by herve91** [comment]
Hi, sorry for the long delay. The fix will be part of the next version that will be released soon.
