### ISSUE TITLE
Automatic Refresh from DB

### ISSUE THREAD

**Issue by markpenn2020** [archi-contribs/database-plugin#164]
First, thank you for this plugin.  It shows a lot of promise for our use cases.  

My use case is as follows.  An AppsModel will represent a list of authorized application building blocks that solution architects (SA) can use to create solutions.  The enterprise architect (EA) would own the AppsModel and keep the "standard" building blocks up to date and those changes will be replicated to any SolutionModels using those building blocks. When the solution is finalized, it will be saved to the DB as the first version of that solution.  Changes will be tracked automatically when the SA changes his specific use of the enterprise building blocks.

My steps.
1. Create a new model and import several hundred applications via CSV, which I'll call AppsModel.  Works as expected.
2. Export that to PostgresDB.  Works as expected.
3. Save and close AppsModel.  Work as expected
4. Open a new model and select the specific applications from the DB I want to import into the new model in force shared mode.  Works as expected.
5. Save that model as SolutionModel and close.  Works as expected.
6. Open AppsModel and change an application that I know SolutionModel is using.  Works as expected.
7. Export those changes to the database, resulting in a new version of SolutionModel.  Works as expected.
8. Save and close SolutionModel.  Works as expected.
9. Open AppsModel.  I expect to see the changes made in AppsModel reflected here, but they are not.  How do I trigger the synchronization between the AppsModel database changes and the SolutionModel?  I don't see a refresh button or any way to set preferences such that SolutionModel applies changes made to AppsModel.

What am I missing?

Thank you in advance for your help.
Mark

**Comment by herve91** [comment]
Hi Mark,

If the solutionModel is saved in an archimate file and not exported to the same database as the AppsModel, then effectively it cannot be automatically updated when the database changes.

But maybe I missunderstood something in your steps ?

**Comment by markpenn2020** [comment]
Thank you for your prompt reply.  I will export SolutionModel to the DB, as you suggested.  Once that occurs, what triggers SolutionModel to see the changes made in AppsModel?

**Comment by markpenn2020** [comment]
Took me a few days to get back to this.  As you suggested, I exported the SolutionModel back to the database, and it works as you indicated it would. 

Some further questions.  In my use case, I would like to maintain a set of standard or approved applications in AppsModel (an enterprise catalog of standard application building blocks).  Creating AppsModel and exporting it to the DB works great to create such a catalog.  

Now, I would like a solutions architect to create a new model, called SolutionModel and populate it from the standard apps defined in AppsModel (selecting approved building blocks from the enterprise catalog).  In my testing, I can select whatever element I want from any element in any model that is stored in the DB.  So, for example, I can import InvoicingApp from AppsModel to include it as part of the new SolutionModel.  Again, this is exactly what I seek.  However, how can I keep the solutions architect from modifying the standard version of InvoicingApp that is stored in the DB.  By default, template mode is the import selection, but I am finding that changes made to InvoicingApp from inside SolutionModel update the version in AppsModel (which is the standard catalog).  

Am I misunderstanding the functionality?  Copy mode creates a new application record in the DB (new UUID).  Shared allows anyone to make updates to the same application with included conflict management.  I was expecting template to create a link to the template application such that any model using it cannot make changes to it.  I have not created a template property yet, as that did not seem necessary since the default is template, which is what I was seeking.

Thank you again,

**Comment by herve91** [comment]
You are right.

- In shared mode, the objetcs share the same UUID, meaning that all the models share the same objects!. Therefore, updating it in any model causes the objects to be changed in all the other models.
- In copy mode, the objects are copied, meaning that a new objects are created with distinct UUID and are distinct from the origianal ones. Therefore, every model can change the objects independently from the others.

There is no way to configure an object to be read-write in one model and read-only in the others.

**Comment by herve91** [comment]
I close this case as I cannot change the way it wiorks. Please do note hesitate to open it back (or open a new one) should you have further questions.
