### ISSUE TITLE
Question : do you have any advise to size a database regarding Model size

### ISSUE THREAD

**Issue by jmonsel** [archi-contribs/database-plugin#166]
I'm looking to estimate db size before exporting models in it , so do you have any advise to size a database regarding Model size

Thank you

**Comment by herve91** [comment]
How do you want me to guess ?

It all depends on your model, the number of elements, relationships, views, pictures ... you've got. It also depends on the database technology you plan to use. You may also considere if you export a screenshot of your views or not, and last but not least, as the plugin keeps all your model history, the number of updates you're doing ...

What you may do to estimate this regarding your own model, is te create a sqlite database on your local hard drive, export your model in it and you'll know.

Should you want a more precise estimate, the database model is provided in the "database structure" folder here in github and you may calculate the space required for each of you.

If you want an example, one of my models contains 9375 elements, 11509 relationships, and 266 views and the archimate file is 17MB. The same model in an sqlite database requires 32 MB.

**Comment by herve91** [comment]
Does it answers your question ?

**Comment by jmonsel** [comment]
Yes, i'm fine with your answer
