### ISSUE TITLE
ACLI : Error when executing Export command

### ISSUE THREAD

**Issue by martinmil13** [archi-contribs/database-plugin#168]
Hello,

I get errors when launching an EXPORT in command line.
My environment is Windows / SQLServer
My command line is like :

__Archi -application [com.archimatetool.commandline.app](https://com.archimatetool.commandline.app/) -consoleLog -nosplash --modelrepository.cloneModel "https://dev.azure.com/xxxxxxxx" --modelrepository.loadModel "myRep" --modelrepository.userName "myUser" --modelrepository.passFile "MyPassFile" --export.database "Database name in the plugin" --export.model.name "MyModelName"__

Errors details on attachments please.

Can you see what happens ?
![2023-07-21 14_28_07-Database import_export plugin v4 9 7](https://github.com/archi-contribs/database-plugin/assets/140171948/7225dd7e-27ae-426e-8f69-fa2c51508631)

What seems curious to me is that the error message speaks of import while I am doing an export...
The export command does not seem to need the name of the model unlike the import (I do not see the option in the online help), is this normal?

Thanks for your help.
Regards
Martine 
(PS please note that I am on vacation tonight for 15 days, I will not be able to respond to any messages)

**Comment by herve91** [comment]
Hi Martine,
Thanks for raising this issue.
As I'm on vacation as well, I'll investigate in few days :)

**Comment by herve91** [comment]
Hi Martine,

I kept the "export" word as it is the way the Eclipse framework references the export to database process. Nevertheless, it is more a "sunc" than an "export" as before exporting  the data, the plugin verifies if a newer version of each Archimate concept exist in the database. If this is the case, the the export process import the newer version from the database before exporting the model to the database.

This said, I conducted some more tests on a MS-SQL database  and even if I didn't experienced the same error message as you, I discovered some other issue. I will fix them and release a new version in the coming days. We'll then check if it solves your issue. If not, I'll ask you some more questions to help me understand what happens.

**Comment by herve91** [comment]
In fact, the plugin has been developped to support several people working simultaneously on the same model.

In that perspective, the situation where while you are working on a model, one of your colleague may export a new version in the database. So when you will do your export, the plugin will detect there are some changes in the database. The rules are quite simple:
- if you updated a component that your colleague has not, then it is exported to the database
- if your colleague updated a component that you haven't, then the plugin updates (import) the uptates to Archi
- if both you and your colleague updated the same component, then the plugin shows you both versions and ask you to choose which one to keep (this is conflict management)


But if you're the only person working on your database, you may safely ignore this mechanism :)

I haven't had time to solve the issue yet, but it's on my todo list.

**Comment by herve91** [comment]
Hi Martine,

I do not understand why you state that this mechanism goes _**against**_ collaborative management of Archi itself.

In fact, there is no collaborative management **_of Archi itself_**. CoArchi is a plugin, just like the database plugin. It has been developped by the same developers, that's the reason why coArchi is highlighted on their website and that they refuse to even add a link to my plugin (like all my other plugins by the way).

They are completely distinct plugings that both allow several architects to work on the same models:
- CoArchi links a model to a Git Repository (1 to 1 relation) and allow to create branches. Besides, updating Archimate concepts using another tool than Archi and coArchi is not supported. 
- The database plugin allows to persist several models in several databases (n to n relation), share components between models (when a component is updated in a model, the other models that share this component are automatically updated), but do not manage branches (model history is linear). In addition, the plugin completely supports that models or Archimate concepts are created or updated using SQL requests.

You just need to use the one that fulfill your needs. If you use two independent collaborative plugins, then you need to manage conflicts in both :)

**Comment by Phillipus** [comment]
> that's the reason why coArchi is highlighted on their website and that they refuse to even add a link to my plugin (like all my other plugins by the way).

That's not correct. We don't link to _any_ third-party plug-ins on the main Archi web-site because we are not responsible for their maintenance or promotion. But we do have an [Other Plug-ins](https://forum.archimatetool.com/index.php?board=7.0) section on the Archi Forum where third-party plug-ins can be discussed and promoted.

**Comment by martinmil13** [comment]
Hello Hervé,
I'm returning to my work on Archi after a long interruption.
I tried unsuccessfully last year to write a batch that automatically exported my model to a database with your plugin.
Before starting this work again, I would like to know if you still maintain your export plugin. I see that the last release dates from last year, I would not want to embark on this complex work if this plugin is no longer maintained.
Thank you for telling me.
Best regards.
Martine


Martine MILETTO
Project Management Officer - Direction des Systèmes d’Information

Tél. 07 62 00 16 46
Le Tholonet - CS 70064 - 13182 Aix-en-Provence CEDEX 5
***@***.***

De : Hervé Jouin ***@***.***>
Envoyé : vendredi 11 août 2023 11:33
À : archi-contribs/database-plugin ***@***.***>
Cc : MILETTO, Martine ***@***.***>; Author ***@***.***>
Objet : Re: [archi-contribs/database-plugin] ACLI : Error when executing Export command (Issue #168)


In fact, the plugin has been developped to support several people working simultaneously on the same model.

In that perspective, the situation where while you are working on a model, one of your colleague may export a new version in the database. So when you will do your export, the plugin will detect there are some changes in the database. The rules are quite simple:

  *   if you updated a component that your colleague has not, then it is exported to the database
  *   if your colleague updated a component that you haven't, then the plugin updates (import) the uptates to Archi
  *   if both you and your colleague updated the same component, then the plugin shows you both versions and ask you to choose which one to keep (this is conflict management)

But if you're the only person working on your database, you may safely ignore this mechanism :)

I haven't had time to solve the issue yet, but it's on my todo list.

**Comment by herve91** [comment]
Hi Martine,

The plugin is still maintained but as my new company does not currently use it, I only correct bugs and update the plugin when new Archi versions require it. I do not plan to add new functionalities in the short term.

Please note that as per issue #175, the plugin does not work as expected in batch mode and I'm currently working on it. A fix will be release soon.

Best regards
Hervé

**Comment by martinmil13** [comment]
Hello Hervé,

Thank you for this feedback, I will therefore resume my project of automating the export of my model.
Thank you for your work,
Best regards,

Martine

De : Hervé Jouin ***@***.***>
Envoyé : vendredi 31 mai 2024 16:27
À : archi-contribs/database-plugin ***@***.***>
Cc : MILETTO, Martine ***@***.***>; Author ***@***.***>
Objet : Re: [archi-contribs/database-plugin] ACLI : Error when executing Export command (Issue #168)


Hi Martine,

The plugin is still maintained but as my new company does not currently use it, I only correct bugs and update the plugin when new Archi versions require it. I do not plan to add new functionalities in the short term.

Please note that as per issue #175<https://github.com/archi-contribs/database-plugin/issues/175>, the plugin does not work as expected in batch mode and I'm currently working on it. A fix will be release soon.

Best regards
Hervé

**Comment by herve91** [comment]
fixed in version 4.9.8 that will be released very soon
