### ISSUE TITLE
Database plugin "Failed to empty Neo4j database" error

### ISSUE THREAD

**Issue by TBryanB** [archi-contribs/database-plugin#169]
I recently had to reinstall Archi and the database plugin.  I installed plugin version 4.9.7.  I'm trying to export to Neo4j, but I keep getting an error message "Failed to empty the Neo4j database".  I can't figure out what's going on.  Any ideas of what I might have done incorrectly when I reinstalled/reconfigured the plugin?  
![Plugin_Error](https://github.com/archi-contribs/database-plugin/assets/112726720/efbbaf0b-08de-486b-a97d-ca67762a90b3)

**Comment by TBryanB** [comment]
Oops.  Pasted the wrong screenshot.  Here's the correct one.
![Plugin_Error](https://github.com/archi-contribs/database-plugin/assets/112726720/418cfc60-d33a-4a16-bdb4-cc601ccc1365)

**Comment by herve91** [comment]
Hi,

I succeeded to reproduce your issue. I'll fix it aap.

Best regards

**Comment by TBryanB** [comment]
Great, thanks.

**Comment by herve91** [comment]
fixed in version 4.9.8 that will be released very soon
