### ISSUE TITLE
error: value too long for type character varying(50)

### ISSUE THREAD

**Issue by DirkMoree** [archi-contribs/database-plugin#17]
When I get this error while exporting a model to Postgres, how can I find the attribute which is too long? Or is there something else wrong?

**Comment by herve91** [comment]
Hi,

You may activate the plugin log file in the preferences.

Best regards
Hervé

**Comment by DirkMoree** [comment]
You mean to set the 4 choices on the Debug tab? I looked at AppData\Roaming\pgAdmin\sessions but I can't find the cause of the problem.

**Comment by herve91** [comment]
I mean that you may configure the plugin to generate a log file and the logfile will provide you information about the error.

If the plugin is configured in "trace" mode, the you also will have the SQL request that generated the error.

Best regards
Hervé

**Comment by DirkMoree** [comment]
Dear Hervé,
I am very sorry but I can't find where I can configure the plug-in. I am looking on https://github.com/archi-contribs/database-plugin/wiki/Preferences, but I don't see any parameter "log-file" or "trace-mode".

**Comment by herve91** [comment]
In the same preferences window than where you defined your database (Edit / Preferences menu, then database plugin on the left).

You then have got a "Logger" tab that allows to configure the logger mecanism. The easiest is to use the "simple mode" where you just need to specify the level and filename.

**Comment by DirkMoree** [comment]
I only see Behaviour and Debug tabs, no Logger? I use plug-in version 2 in Archi 4.

**Comment by herve91** [comment]
I beleive you so not use the latest version. Here is the preference page you should have:
![preferences](https://user-images.githubusercontent.com/9281982/29166599-5c725134-7dc7-11e7-9f20-04d115cfd723.png)

Please upgrade to latest version. This should solve your issue.

**Comment by DirkMoree** [comment]
Okay, I upgraded, and made a new database and tables in Postgress with PostgreSQL script. But now I got in Archi-export: "the database is connected but the nessessary tables have not been found." When I confirm create, than comes "Images already exists". (I'am sorry, I'am not so very technical...)

**Comment by herve91** [comment]
Don't be sorry, I'm here to help you :-)

From few months now, the plugin is able to create its own datamodel. What I can suggest is that you drop the tables you manually created and the first time the plugins connects to your database (either when you click on the "check" button on the preference page, or when you import or export), it will create what it needs.

After that, when you upgrade the plugin from one release to another one, the plugins automatically deals with the database tables updates if needed.

This way, you do not need to manage SQL requests manually anymore.

If doing this you continue to have an error message, you may configure the plugin in trace mode and send me the last 50 or so lines of the log file that I can understand what happens.

Please be aware that sending me these lines will give me inforamtion about your model. So it it contains sensitive or confidential data, you may send me only the lines that contain an error message (lines with ERROR keyword and java exceptions if any).

**Comment by DirkMoree** [comment]
[DatabasePlugin error 20170810.txt](https://github.com/archi-contribs/database-plugin/files/1215103/DatabasePlugin.error.20170810.txt)


Okay, that helped me. I'am 1 step further now. I exported 1 stand-alone model to the Postgres database, and now I want the merge it with a existing container-model (contains 2 models). So I exported the container model to the same database, but than I get again the error it all started with. See attached file.

**Comment by herve91** [comment]
If you were in trace mode, could you please send me the SQL request that is shown just before the error lines (if the information is not sensitive or confidential of course) ?

**Comment by DirkMoree** [comment]
See attached logfile (not sensitive or confidential).
[DatabasePlugin error 20170810 trace.txt](https://github.com/archi-contribs/database-plugin/files/1215161/DatabasePlugin.error.20170810.trace.txt)

**Comment by herve91** [comment]
Ok, I see the issue.

you tried the version 1 of the plugin under Archi 3 andconverted it to Archi 4. The point is that the version 1 of the plugin was modifying the IDs to store metadata. The version 2 of the plugin manages this metadaat differently.

What you need to do is to replace these IDs to Archi 4 IDs andto acheive that, you've got an option when you right-click on the model line in the tree (left of Archi) called "**convert old fashion IDs to Archi4**"

The the export will succeed.

**Comment by DirkMoree** [comment]
Okay, that helped (I already converted the stand-alone model, but forgot the shared model); the export succeeded. But now I try to import the merged stand-alone model and the shared model from PostGres in one new shared model in archi. But I get only the stand-alone model?

**Comment by DirkMoree** [comment]
So I expected 1 imported shared-file containing 3 models: 1 former stand-alone model with 1 model, and 1 formed shared model with 2 models.

**Comment by herve91** [comment]
I do not understand what you wish to achieve.

Basically, every object in Archi has got internal ID. What my plugin allows is to export them in a central repository (database) and to import them back in another model, keeping their ID.

It means that **the same** element, relationship or view can be in several models. Every modification made on one of them in one model will be available to the other models (not real time of course because the plugin is an import/export plugin only).

I know I'm late on the documentation, sorry about that.

**Comment by DirkMoree** [comment]
Dear Hervé,
What you describe is exactly what I want! I have 3 models where different people work on. Each model has its own subject: one for organization, one for applications,  and one for processes and data. But I want to draw relations between those 3 models. And  after changes (each model will have there own modification frequency), I want to synchronise that changes with the shred model-database. 
I already succeeded to create relations between 2 models in a shared model thanks to your plug-in!  Now I want to add the third model. So I exported the already shared model (which contains the 2 original separated models), and I also exported the third model. So far so good.  Starting the import I see in the database preferences 2 models: the already shared model, and the added third model. That looks good. But when I did the import to get a shared model that contains the 3 models, the result was only the third model which I wanted to add.

**Comment by herve91** [comment]
What you wish to acheive is a kind of meta model: one model that include the 3 others.

As I do not have this requirement in my company, I did not implement it but I will think about it and it may be possible in a near future :-)

Using a single model, uase by your 3 teams at the same time will not work either because you will need to manage conflicts (when people export different values ofthe same object). The conflict resolution is dealt inside the plugin, but it may be quite annoying and time consuming for your users.

What I suggest is that you create your 3 models (organization, applications and processes).

The you create a 4th one inside which you import the view of all the 3 other models. Of course, when you import the views, you also import all the corresponding elements and relationships. You will also be able to create relationships between all of them (because they are now inside a single model, the 4th one).

Please be aware that every update in any view (using the organization, applications, processes or even the 4th model) will be seen in all the other models which include the view.

**Comment by DirkMoree** [comment]
I already succeeded to merge 2 models and make relations between them (processen and applications) in the shared model. Looking at the documentation it should be possible to add a third model?
There are not many users, in fact only one per model. And in my project there will be a few updates next coming weeks, and when the 3 models are complete, the shared model will be stable for some time. So there is no much time consuming for users to deal with consistence.
Your suggestion is quite near the story I wrote above. What is specific is that the model with softwareapplications comes from another application in which upgrades en couplings between applications are registered and kept up to date. The other models (Processes and Organization) are manually maintained and the relations between the 3 type of models too. So the only reason I need a frequent Import/Export for, is the generated applicationmodel with new applicationdata which I can update in the shared model and check / update relations with the organization en processes.
So I really think that what the plugin supports should be possible with this. I suggest that I try the export and import again, (maybe I made a mistake), and when the same problem occurs, I send you the Postgres-database in which the 3 models are imported, so you can analyse if there is a problem. Or you can see what is necessary to develop in a near future to achieve this goal. Anyhow thank you very much for your help so far, and I hope my projectgoal will succeed with your help.

**Comment by herve91** [comment]
You're welcome.

I close this HitHub issue as you do not have error message while exporting. I suggest we continue to work together using mail as this is more telling you how to use the plugin.

My email: herve.jouin@gmail.com.
