### ISSUE TITLE
Cannot find installable archive file nor .archiplugin file on GitHub

### ISSUE THREAD

**Issue by koalabi** [archi-contribs/database-plugin#170]
(The subject tells it all) I'm very interested in this plugin but I don't see any binary file. Is building it from source the only option?

**Comment by herve91** [comment]
You'll find the binary in the releases section: https://github.com/archi-contribs/database-plugin/releases

**Comment by koalabi** [comment]
Great! Thanks. Strange that this folder is not visible from anywhere, contrary to ther repositories (unless I'm mistaken).

Issue may get closed.

**Comment by koalabi** [comment]
Question answered.
