### ISSUE TITLE
Suggestion - allow exporting via CLI

### ISSUE THREAD

**Issue by joshliberty** [archi-contribs/database-plugin#177]
Hi,

First of all thank you for the plugin - I use it regularly and it's extremely useful (especially now that neo4j export has been fixed!).
I wanted to propose a suggestion which will greatly enhance the functionality of the plugin, specifically to allow exporting the model using a CLI command.

The idea is to be able to run this as part of a github pipeline, so that when using coArchi to push model changes to Github, it'll be possible to automatically update databases with the new contents.

Thanks,
Josh

**Comment by herve91** [comment]
Hi Josh,

My plugin already implements the CLI commands.

**Comment by joshliberty** [comment]
@herve91 that's amazing! Is there any documentation on how to use it?

**Comment by herve91** [comment]
I haven't updated the documentation for a while and need to rework it from scratch. You can use the help option of the CLI command line for complete options.

You need to first declare the database in the plugin before it can be used in CLI commands.

You may then use this command line as a start:

```
Archi -application com.archimatetool.commandline.app -consoleLog -nosplash --abortOnException --modelrepository.loadModel . --export.database db_name
