### ISSUE TITLE
Overwrite data model in existing sql database

### ISSUE THREAD

**Issue by wrakesh2005** [archi-contribs/database-plugin#179]
I am unable to see option overwrite or append while exporting ArchiMate model to sql database , archi version is 5.4.3 and database plugin is 4.9.8 i am using

**Comment by herve91** [comment]
There is no such option. The plugin versions **all** the Archimate components. When a composant is not modified, it keeps its version and is not exported to the database (it is just referenced a being part of the current version of the model). On the opposite, when a component is modified, then its version number is increased, and this new version is exported to the database.

**Comment by wrakesh2005** [comment]
Thanks for confirmation
