### ISSUE TITLE
Cannot connect to mysql with archie 3.3.1 - "Cannot load 'org.mysql.Driver' driver"

### ISSUE THREAD

**Issue by funky3l** [archi-contribs/database-plugin#2]
Hi,
Using database-plugin 0.2. and 0.3 - no difference in behaviour.
I cannot connect to MySQL as the following message is shown: "Cannot load 'org.mysql.Driver' driver".

Help :-).
Best regards,
Paweł Szewczyk

![2016-05-09 08_25_43-clipboard](https://cloud.githubusercontent.com/assets/19260308/15105171/a79f2c02-15bf-11e6-8aef-04a032696884.png)

**Comment by herve91** [comment]
Dear Paweł,

I effectively had a bug in my plugin regarding the MySQL driver. I
corrected it and published the JAR again on GitHub.

Please fill free to drop me a line should you have any other issue.

Best regards
Hervé

2016-05-09 8:28 GMT+02:00 funky3l <notifications@github.com>:
