### ISSUE TITLE
Type archimate:node

### ISSUE THREAD

**Issue by ZinovyevMaxim** [archi-contribs/database-plugin#20]
Hi!

Herve after exporting to the database components with the second type of figure in the database field type is NULL. In this regard, new installations of archa on other computers open mappings in imported ones is not correct instead of cubes squares, it is necessary to manually change the type of figure :).

Tell me the reason

  Initial model
       Element xsi: type = "archimate: Node" name = "tomcat-cvr_win2008R2" id = "08389cdf-3f26-4f96-b234-1cffc140b783" type="1"

Import from the database
       Element xsi: type = "archimate: Node" name = "tomcat-cvr_win2008R2" id = "08389cdf-3f26-4f96-b234-1cffc140b783"

**Comment by herve91** [comment]
Hi Maxim,

I just did test with a model containing 2 nodes, one using type = "0", the other type = "1" and the export / import works correctly ...
![archi 2 nodes](https://user-images.githubusercontent.com/9281982/29449583-9475afd8-83fb-11e7-9a48-057d27f00364.png)

Could you please provide me more information (your OS, version of Archi and version of the database plugin) ?

Thanks and regards
Hervé

**Comment by ZinovyevMaxim** [comment]
Plugin 2.0.6
Archi  4.0.1
OS Windows 7

**Comment by ZinovyevMaxim** [comment]
On my computer everything works fine, there's no one else on it, I looked xml source the model, it does not specify the type of the element. 

In my database
SELECT count (1) FROM ITA.elements where class = 'Node' union
SELECT count (1) FROM ITA.elements where class = 'Node' and type is not null;
# Count (1)
2156
0

**Comment by herve91** [comment]
closed as no answer
