### ISSUE TITLE
Archi crashes when one clicks on Purpose or Release note

### ISSUE THREAD

**Issue by deconstructo** [archi-contribs/database-plugin#22]
Hiyah,

I'm running Archi 4.0.2 and database plugin 2.0.7 against a local MySQL repository.

I can successfully export and import models to/from the database. However if I click on the Purpose and Release Note fields, Archi exits.

Nothing turns up in the log4J log file,

**Comment by herve91** [comment]
Hi,

What I can suggest is to run Archi with the console activated (i.e. running "archi.exe -consolelog") and check in this console if there is an explicit error message.

Best regards

**Comment by deconstructo** [comment]
No explicit error message that I can see...

**Comment by herve91** [comment]
Hi,

Without any error in the plugin's log file nor on the Archi's console, then I cannot do much I'm afraid.

Best regards
Hervé
