### ISSUE TITLE
Orphaned Elements

### ISSUE THREAD

**Issue by jonnydab** [archi-contribs/database-plugin#26]
Can you provide a mechanism to clean up orphaned elements without hacking the database? I have two projects. I've imported elements from one project into the other using shared, then deleted from the original and then deleted from the new and the elements keep appearing in the import element even though they're not in either project anymore. Thanks

**Comment by herve91** [comment]
Hi,

House keeping is effectively not yet developped. I planned two kinds of deletion:
   - soft: it is just a flag that will allow to hide objets but they will remain in the database as history (meaning it will be possible to undelete them).
   - hard: removing the objects from the database, but without any way of undelete them.

I'll give it a higher priority and let you know as soon it is done.

Best regards
Hervé

**Comment by herve91** [comment]
Closing this request as delivering a collaborative plugin has got even higher priority ...
