### ISSUE TITLE
Element Import folder structure aware

### ISSUE THREAD

**Issue by jonnydab** [archi-contribs/database-plugin#27]
Import of the elements doesn't seem to be folder hierarchy aware. Is it possible to add an option that would import the containing folder hierarchy if it makes sense form the root?

i.e. if I have 
Application
    - Entities 
         --- Customer <<Data Object>>

If I import Customer, it should import and either put it in the folder structure, or if it doesn't exist create the folder structure. You could switch on and off this behaviour

**Comment by herve91** [comment]
Hi,

Linking folders between models do not make sense as moving a component from one folder to another one means removing the component from the source folder but the component should not be removed from the model, right ?

What could rather be done, is to consider a folder as a group of components from an import point of view.

I mean, when selecting a folder during the import process would import the components located in this folder, but without linking the folder itself.

So updating the folder afterwards in any folder will not impact the other folders in the others models.

Would it be enough for you ?

Best regards
Hervé

**Comment by jonnydab** [comment]
Hi

I think that would be useful. But I was thinking more along the lines of replicating a folder structure in a model rather than linking or sharing it. Another way might be to allow archi to support nested elements just like many other tools. I.e if I have a capability taxonomy or entity taxonomy I can put child elements underneath parent elements. This would allow you to conceal complexity with the model hierarchy which is one of the reasons I need the folder structure. I will send this request to the main Archi project.

Thanks

**Comment by herve91** [comment]
Hi,

Importing nested components will be more tricky because nesting in Archi is just a question of graphical presentation. Elements are linked with relationships and can be nested in one view but not nested in another one. So For the moment I haven't got any solution for this case.

But implementing folder import as a folder structure (and content) replication should be feasible.

I keep this thread open and I'll let you know when it is done.

Best regards
Hervé

**Comment by herve91** [comment]
Hi

I'm working on this point in version 2.1 (that is in beta release 3 at the moment).

Best regards
Hervé

**Comment by herve91** [comment]
Hi,

Just to let you know that importing a folder is not (yet) possible in the 2.1 beta 9 version but that I haven't forgotten your request and that it still is on my todo list.

Best regards
Hervé

**Comment by herve91** [comment]
Closing as too complex to implement ... I won't do it ... Sorry ...
