### ISSUE TITLE
Can you explain how the x, y, height, width are calculated?

### ISSUE THREAD

**Issue by GeoffMurray** [archi-contribs/database-plugin#30]
I have been able to pull images from the DB, and display them. Trying to create the corresponding image maps. 

Using the models, objects in model, views in model tables to generate the images and image maps. 

Seems like the coordinates for the objects in the view that exist in the D/B are based on the view plane located in Archi. 

When the model is exported. the images are typically smaller (ie, the screenshot field is smaller than the image displayed to remove some of the whitespace), and so the x, y, height, width of the objects that are supposed to be on the map don't align. 

It's almost like there is a perhaps view offset that is internal to Archi that is not exported. Perhaps something that locates or centres the model view on the page, and the actual coordinates are drawn from that. Maybe it's some kind of % sizing of image or something.

Is it possible the export model is missing something like that?

**Comment by herve91** [comment]
I'm not aware of any view offset. The coordinates, width and height are properties of the graphical objects. I export them as they are without any scale nor any shift. And when I import back the graphical objects, I set the x, y width and height as they are stored in the database.

**Comment by GeoffMurray** [comment]
Ok - thanks. What leads me to think there are some other offset or sizing information associated with the model is that when I do the HTML export (ie, HTML report), the x,y locations match the HTML viewable map, but are very clearly different from the coordinates in the database. 

However, the difference is not constant across views, and the difference appears to be related to where the objects are centred in the viewport window in Archi on the view, vs where it shows up on the HTML view. The Jasper HTML export properly calculates the offsets in comparison to the screenshot generated image, so it makes me think there must be something it's doing to do that. I'll try referencing this question in the Archi forums to see if there is some additional information that would be useful.

**Comment by GeoffMurray** [comment]
I asked the Archi side of this question in this post: https://github.com/archimatetool/archi/issues/347

**Comment by herve91** [comment]
The version 2.1 of the plugin (now in beta 3 version) allows to specify the border width and a scale factor.

I hope this will suits your need.
