### ISSUE TITLE
V2 - Compatible with MS SQL Server database ?

### ISSUE THREAD

**Issue by isthes** [archi-contribs/database-plugin#31]
Hello,

The list uof database compatibility didn't mentionned MS SQL Server. Does it mean that it was not possible to use is as repostory or is it possible to add manually MS SQL Server driver to manage that ?

Thanks for your answer and nice job for this plugin.

Laurent Patel

**Comment by GeoffMurray** [comment]
I use MS SQL, and it definitely works :-)

**Comment by herve91** [comment]
Hi,

The database plugin is definitively working with Microsoft SQL Server. I also included a procedure to use the integrated security mode (ie Windows authentication).

SQL Server was missing in the databases list, this was a mistake. I just corrected it.

Thanks and regards.
Hervé
