### ISSUE TITLE
Update jar to 2.1

### ISSUE THREAD

**Issue by eistomin** [archi-contribs/database-plugin#32]
Hello Herve!
Can you please update jar to reflect https://github.com/archi-contribs/database-plugin/commit/e5f4feeea88cafdd12fd7301cf6dd8ed80da529a changes - v 2.1?

I'm trying to compile using Eclipse, a lot of import error - all on my side, seems like code OK ^)

**Comment by herve91** [comment]
Hi Eugene,

The 2.1 version is still in beta state and some anomalies are still beeing addressed. I believe I should be ready to release the .jar file in about 2 weeks time.

But if you're ready to test it and send me all the bugs you found, I'm ready to send you the jar file. but please remeander that at thisstage, it is not ready (yet) to be used on your production database.

Alternatively, if you wish to compile my code, I suggest you download the latest commits that fix the errors you're experiencing.

Best regards
Hervé

**Comment by eistomin** [comment]
Yes, i'm ready to test - primary goal is to build up "Organisation prototyping platform" using Archimate, Telegram & "Flourishing Business Canvas" concept.
So i have an Archimate-to-Telegram abstraction layer using sqlite export by Database-plugin

**Comment by herve91** [comment]
You'll find it in the test folder.

Please remember that this version is for testing purpose only and should not be used on a production database, and do not forget to open issues if you discover misbehaviours.
