### ISSUE TITLE
Cant install plugin on mac

### ISSUE THREAD

**Issue by banthaza** [archi-contribs/database-plugin#37]
Hi guys, 

The jar file doesn't seem to be compatible with the import plugin on mac. Has any one go some suggestions on how to configure it for mac? (note: import plugin requests a zip file
<img width="591" alt="screen shot 2018-05-15 at 08 54 03" src="https://user-images.githubusercontent.com/9672724/40041244-9afa6974-581d-11e8-8587-4feece34f8e6.png">

**Comment by herve91** [comment]
Hi,

The plugin cannot be installed using the "Install Archi Plugin-in" menu entry. The JAR file must be manually copied to the Archi.app/plugins folder.

If you fail to do it this way, I can generate a zip file that is compatible with the "Install Archi Plugin-in" menu entry.

Please let me know.

Best regards
Hervé

**Comment by herve91** [comment]
closed as no answer
