### ISSUE TITLE
Currently displayed page contains invalid values

### ISSUE THREAD

**Issue by kaiserghetto** [archi-contribs/database-plugin#39]
I used the plugin once before, but now when I launch the Preferences pane and look for the Database Plugin, I get this error message with the title "Could Not Accept Changes".

This is on Win2016

**Comment by herve91** [comment]
I haven't tried my plugin on Windows server edition, only Windows 7 and 10.

I'll try to find a Windows 2016 server to do some testing ... Meanwhile, could you please confirm the version of Archi and plugin you're using.

You also need to open the Java console when running Archi (i.e. running "Archi.exe -consolelog") and send me the Java error message(s) that will be printed in that console.

Thanks and regards
Hervé
