### ISSUE TITLE
Plugin 2.1 Beta 8 - missing data fields?

### ISSUE THREAD

**Issue by GeoffMurray** [archi-contribs/database-plugin#40]
The documentation for the plugin describes the data model. However, the table view_objects does not appear to have a view_id connection anymore in my table definition. 

![image](https://user-images.githubusercontent.com/28354503/43865800-7662214a-9b18-11e8-9310-a6d4c103d008.png)

This is the SQL table definition. I'm trying to understand how to link the objects to the views without such a field.

These table definitions were created when I blew away my prior tables, and re-exported my model to my database. So, not SQL scripts I can see, but rather done directly in the plugin. 

/****** Script for SelectTopNRows command from SSMS  ******/
SELECT TOP (1000) [id]
      ,[version]
      ,[class]
      ,[container_id]
      ,[element_id]
      ,[element_version]
      ,[diagram_ref_id]
      ,[border_color]
      ,[border_type]
      ,[content]
      ,[documentation]
      ,[hint_content]
      ,[hint_title]
      ,[is_locked]
      ,[image_path]
      ,[image_position]
      ,[line_color]
      ,[line_width]
      ,[fill_color]
      ,[font]
      ,[font_color]
      ,[name]
      ,[notes]
      ,[text_alignment]
      ,[text_position]
      ,[type]
      ,[x]
      ,[y]
      ,[width]
      ,[height]
      ,[created_by]
      ,[created_on]
      ,[checksum]
  FROM [RD].[archi].[views_objects]

**Comment by GeoffMurray** [comment]
Ah, actually, just to confirm, I probably should be looking here for that data: 

https://github.com/archi-contribs/database-plugin/blob/master/v2/sources/help/img/databaseStructure.jpg

**Comment by GeoffMurray** [comment]
I think I'm ok. Just working through it all.

**Comment by herve91** [comment]
Plugin version 2.0 and before used two columns called "view_id" and "view_version" in the "views_objects" table. So each time a view was exported, all the views objects needed to be exported which is bad from performance and disk space perspective. Importing and exporting a views required also a specific procedure that was distinct from importing elements and relationships.

Plugin 2.1 introduces a new table called "views_objects_in_view" that links the views objects to their view, So in case a view has not been updated, we do not need to export its views objects anymore.

Same for views connections.

If you're using the plugin version 2.1 beta 8, then you need to check the database structure version 209.

Hope this helps.
Please do not hesitate should you require more information :)
