### ISSUE TITLE
Wondering if the new options for image export actually solve the problem I had?

### ISSUE THREAD

**Issue by GeoffMurray** [archi-contribs/database-plugin#41]
Wondering if you can explain what this actually does to the data created?

**_Allow to specify border width and scale factor for views screenshots_**

For example, if I use a scale factor, does it change the screen shot image itself, or does it adjust the x/y/height/width factors that are exported to the table. 

I'm trying to understand if the new version solves the problem I discuss here: https://github.com/archi-contribs/database-plugin/issues/30 and here: https://forum.archimatetool.com/index.php?topic=486.msg2726#msg2726

The longer forum conversation talks about an image shift, is that what the pixel border does? 

I'm still seeing very large image blocks defined by the x/y/height/width values (at 100% scaling) well beyond the size of the actual image that gets generated.

**Comment by herve91** [comment]
Indeed, these options have been created following your requests and I hope they solve your problem :)

The screenshot taken by the 2.0 plugin had hard coded parameters (full size picture, with a 10 pixels border around). The 2.1 plugin allows to change these parameters.

Here are how they work:
   - The  scale factor allows to change the size of the picture. It is applied on the width and height (i.e. 50% means reduce the width and the height by half)
   - The border width allows to change the border width (can be set to 0 to ease your objects coordinate calculation)

Hope this helps
Best regards

**Comment by GeoffMurray** [comment]
If I change the default export percentage, and perhaps offset, for the database connection, that doesn't automatically export the image views the next time I do a DB export. I have to touch the view itself as well.

Also, just generally, I simply cannot figure out how to make the coordinates in the db match the image output, even by playing around with the images. I'm sorry, I just don't get it.

**Comment by herve91** [comment]
In version 2.0.7 and prior, I created a new view version when the view content changed.

In version 2.1, I changed the test and create a new view version when the view itself (as a container) changed, not when its content changed.

I believe it was a mistake and I will roll back this change to the old behaviour. Thanks for pointing me to this.

As per the objects coordinate, this will be quite complicated. What you need to know:
- Archi's screenshot procedure provides a picture that is moved to the top left corner
- you may add (or not) a fixed size border around
- an object coordinates are specified from its container which can be the view or another object.

So you first need to calculate the horizontal and vertical shift by getting in the database the MIN(X) and MIN(Y) for components that are directly inside the view (and not inside another object) (i.e. WHERE CONTAINER_ID = <your view ID>).

Then, you just need to apply this shift for all the objects that are directly inside the view.

For objects that are inside other objects, you just need to add the coordinates of the container to the coordinates of the object itself.

Hope this helps

**Comment by herve91** [comment]
I'm sorry ... I wrote too quickly and gave you false hope ...

Implementing such columns is too complicated and I needed to rollback. There are external factors that can change a view without changing components (like enabling gradients in Archi preferences) so it would completely change the way I detect the components to export and those that I do not need to export.

So what I've done, is that I created 2 new columns in the views table:
- screenshot_scale_factor
- screenshot_border_width

and Included the screenshot in the views checksum. So if the screenshot changed, for whatever reason, I export the view itself (as a container) but I did not changed my algorithm that calculate the view objects that need to be exported.

Nevertheless, here is the algorithm to calculate the coordinates in the screenshot from the coordinates in the view ...

You must know that the objects coordinates in the views are calculated from their container, which can be the view itself, but can be another view object. So the container is not the view, you must offset the object coordinates with the container coordinates.

This is pseudo code, you must adapt it to the language you use ...

`
if ( container_is == view_id ) {
     x_offset = screenshot_border_width;
     y_offset = screenshot_border_width;
} else {
     x_offset_x = x coordinate of object container in screenshot;
     y_offset_y = y coordinate of object container in screenshot;`
}

scale = screenshot_scale_factor / 100.0;
x_in_screenshot = (int) (x_in_view * scale) + x_offset;
y_in_screenshot_y = (int) (y_in_view * scale) + y_offset;
width_in_screenshot_width = (int) (view_width * scale);
height_in_screenshot_height = (int) (view_height * scale)
` 

It will be available in the next beta release of the plugin. I hope this helps.

Please do not hesitate to ask if you require more assistance.

Best regards
Hervé

**Comment by GeoffMurray** [comment]
Hervé, just wondering if this is in your beta9.5 Release? I'm more than happy to try it out. I may try and create a view or function (or view and function :-)) that does the math you talk about for my SQL db, just to see if I can understand how to make it work.

**Comment by herve91** [comment]
Hi,

yes it is :-) And as usually, I did not do a lot of testing on MS SQL databases, so I'd be more than happy if you could test it.

Thanks and regards
Hervé

**Comment by GeoffMurray** [comment]
Ok - I just cannot get the screen coordinates to match. 

For example, if I use the File --> Report --> HTML option, I get an HTML dump of my model. When I go to the views, the sensitive areas exactly match the objects on the screen.

When I use the coordinates exported by the DB plugin (even taking into account all the math above), I get map areas that just don't align. It seems to be offset almost randomly by how much whitespace is not exported in the images (ie, if I pull the elements of a view down in the Archi window, and then export it), the misalignment is more pronounced. Also, the sizing of the map sensitive areas for the objects in the database export does not match the map sensitive area sizes for the FILE/Report/HTML option. 

I'm not really sure how else to explain it. It should be something you can easily see by comparing the HTML of a standard report to what the database shows. You should be able to see it with a very small number of objects. Again, much more pronounced when the objects are low down in the Archi editing plane, with lots of whitespace at the top. 

It's almost like there's still a missing internal offset and scale that's not being accounted for in the database export math.

**Comment by herve91** [comment]
Hi,

I just did the test and used an online diff checker (https://online-image-comparison.com).

Images are identical ...

Best ergards
Hervé
