### ISSUE TITLE
Import/Export - Can't not import

### ISSUE THREAD

**Issue by isthes** [archi-contribs/database-plugin#43]
Hi,

I don't understand why I can not import model from database to my local repository (if previously existing). I got the following error message when I try to import :"A model with ID xxx already exists. cannot import it again."

I am explaining the case :
- I have a model named Toto.archimate in my local repository.
- I exported the model to MS SQL Server database with success.
- A teammate imported the model (into void models tab), and modified it, and exported sucessfully the model with modification.
- I try to import the new version of the model, to see the modification and I got the previous mentionned error.

It is not possible to work in parallel mode with this plugin, because I can not load a new version of database model without deleting my local one, so if I made modification, I lost them.

I don't understand what the problem is. Please help !!!

Archimate version 4.2 and database plugin 2.0.7b.

Thanks for your answer.

**Comment by herve91** [comment]
Hi,

What happens is that you cannot have two models which have got the same internal ID.

So if your model is already opened in Archi (either from an Archimate file, from the collaborative plugin , or from the database plugin), then the database plugin warns you that you cannot import it as it already exists in Archi.

So you've got two options:
1- if you wish to **replace** your actual model in Archi by the version of your model in the database, then you just need to close your model in Archi, then import it from the database.
2- if you wish to **merge** the changes you've done in your model in Archi and the version of your model in the database, then you need to upgrade the plugin to the version 2.1 (which is currently in beta release 9.6) and **export** your model to the database. Yes, I wrote export ... as in version 2.1, an export is in fact sync:
- all the components updated in your database are imported from the database into Archi (thus created or updated)
- all the components updated in Archi are exported to the database
- all the components updated in Archi and in the database generate conflicts that need to be manually solved

Best regards
Hervé

**Comment by isthes** [comment]
Thanks for your fast answer.

Have you forecast a date for the next release ?

Sincerely yours,

**Comment by herve91** [comment]
It is under heavily testing at the moment.

I cannot commit to any formal date but it is a question of days now :-)
