### ISSUE TITLE
Cannot export to neo4j database

### ISSUE THREAD

**Issue by rich-biker** [archi-contribs/database-plugin#44]
**Archi database plugin** 2.1.1
**Archi** 4.3.0
**Neo4j** 3.3.1
**Mac OS** 10.14

I'm trying to export a simple model (validated, no errors) to NEO4J and I'm getting an error "Cannot merge node using null property value for type":

<img width="677" alt="screenshot 2018-09-28 at 10 51 26" src="https://user-images.githubusercontent.com/18450552/46201907-45552800-c30d-11e8-9413-0cdcd02e5d24.png">

Any ideas?

**Comment by rich-biker** [comment]
Here's a fatal debug trace
[DatabasePlugin.log](https://github.com/archi-contribs/database-plugin/files/2427779/DatabasePlugin.log)

**Comment by rich-biker** [comment]
Found the offending merge statement in a more detailed trace file.


MERGE (new:elements {id:'67ed3e6c-d8e0-4d5f-a6df-c9ed68f0df40', version:1, class:'BusinessActor', name:'Fred', type:null, documentation:'', checksum:'f3731d97cff6450f09cf0135b937a5a6'})

It doesn't like **type:null**

[DatabasePlugin2.log](https://github.com/archi-contribs/database-plugin/files/2427790/DatabasePlugin2.log)

**Comment by rich-biker** [comment]
Despite finding the statement, I didn't mean to close this (oops) - it's a problem in the plugin, I guess?

**Comment by herve91** [comment]
I'll have a look when I come home this evening and I'll let you know ...

I never came to this kind of issued during my tests but I must admin that my Neo4J tests are quite light :(

**Comment by jbsarrodie** [comment]
@herve91 Has your plugin been tested with Archi 4.3 (which includes some changes around properties managements) ? Could this be related?

**Comment by jbsarrodie** [comment]
> but per my understanding, you changed the way properties can be set, but the properties class has not been changed, right ?

Right, underlying EMF classes are not changed, so this should not affect this plugin. I just wanted to make sure this was not linked in some strange ways.

**Comment by herve91** [comment]
Thank you, I really appreciate your suggestion because I can easily miss something :-)

**Comment by rich-biker** [comment]
I’m no expert, but I agree that a MERGE is the right command. It would work without the type:null clause too, but I’m not sure what effect that would have later on when you want to set it. 

Richard.

**Comment by herve91** [comment]
To be honest, I couldn't spend enough time on this this weekend ...

So I preferred to rollback the requests to CREATE to provide you with a quick fix and I'll work back on the merge when I have more time.

Best regards
Hervé

**Comment by herve91** [comment]
I close because I won't have time to do it ... Sorry ...
