### ISSUE TITLE
Export/Import option not visible in Menu Linux

### ISSUE THREAD

**Issue by omerule** [archi-contribs/database-plugin#46]
Good afternoon,
I'am using Linux Fedora 32 and 64bit  with Archi.
I downloaded the jar file in plugin folder and restart Archi.
Only the Database Option is not visible in de import or export menu.

Is there something extra i should do besides installing the plugin or is there a extra dependency I must use?

Ps if i use Archi from the commandline i get this message:
!MESSAGE Unable to access file "plugins/org.archicontribs.database_v2.1.3.jar!META-INF/MANIFEST.MF".

Yours kindly
OmeRule
The Netherlands

**Comment by herve91** [comment]
Hi,

I believe the JAR file you got is corrupted. It's size should be 20 683 995 bytes. The easiest way you can get the file is to select the jar file, then click on the download button on the right.
![image](https://user-images.githubusercontent.com/9281982/46908774-05ef2400-cf28-11e8-8ca7-9e634e35c098.png)

Please tell me if this solves your issue.

Best regards
Hervé

**Comment by omerule** [comment]
Thank you indeed it solved the issue.
And if you get a error in Fedora "headless exception" install 
sudo dnf install java-1.8.0-openjdk
