### ISSUE TITLE
wrong version of the plugin displayed in the preferences

### ISSUE THREAD

**Issue by odulek** [archi-contribs/database-plugin#48]
I have version  2.1.3 installed.
However in Preferences > database plugin, the "actual version" field displays 2.1.3

**Comment by herve91** [comment]
2.1.3 version displays 2.1.**2** instead of 2.1.**3**.

Version number fixed in release 2.1.4.

Thanks for pointing me this error.

Best regards
Hervé

**Comment by odulek** [comment]
Thank you
Best regards
Olivier
