### ISSUE TITLE
Neo4j archidatabaseplugin error

### ISSUE THREAD

**Issue by jbaekey** [archi-contribs/database-plugin#5]
When attempting to use Archi 3.3.2 with database-plugin 0.12 and Neo4j, I was receiving an error window stating "Cannot get the database version from archidatabaseplugin table."  I found that i could not use 0.12 with Neo4j without adding a node labeled archidatabaseplugin with  a property labeled version with a text value of 3.

**Comment by herve91** [comment]
Yes, you  are right, this was not described in the installation procedure.

I updated the wiki and added a new script file : create node (neo4j).cql
