### ISSUE TITLE
import of views

### ISSUE THREAD

**Issue by jmiller9591** [archi-contribs/database-plugin#50]
Hi Hervé.

Found with database plugin 2.1.4, that it seems I am unable to import a view in shared database.  I am using a mac o.s. 10.14.1 (Mohave) with a local MySql 5.6 database.  I also had a colleague try with his p.c. with same results.  He was connecting in over network to my laptop MySql server.  Both of us are able to bring models from the database into Archi 4.3 o.k. and we can export back out to the database fine as well.

I must not be able to figure out how to enable trace logging (can you help me in this regard?)  In the preferences menu for the "database plugin -> Logger tab", I selected "Expert mode" and "include SQL requests in trace mode".  Selected "Apply and Close"  The file contents are below:

2018-11-04 04:31:29 INFO   537:DBPreferencePage                         - Logger initialised.
2018-11-04 04:31:37 INFO  1179:DBGui                                    - Counting model's components
2018-11-04 04:31:37 INFO  1179:DBGui                                    - Connecting to the database ...
2018-11-04 04:31:37 INFO  1179:DBGui                                    - Checking the database structure...
2018-11-04 04:31:37 INFO  1179:DBGui                                    - Getting list of views from database ...
2018-11-04 04:31:42 INFO  1179:DBGui                                    - (1/1) Importing view "F5".

Thanks as always for your help!

**Comment by herve91** [comment]
Hi,

Thanks for pointing out this anomaly. I'll conduct some tests and I'll let you know ASAP.

Best regards
Hervé

**Comment by herve91** [comment]
closed by mistake

**Comment by herve91** [comment]
Hi,

I must admit it's not been a long time I've got a MAC, so I never tested te plugin update on MAC. I'll check this point. Thanks for the information.

Regarding the view import issue, 2.1.5 does not change anything as it did not change the view import method. 

But with your log file, I understand what happens : you're using diagram model references. This means that dragged and dropped views inside other views ... And visibly, I've got a recursivity issue with this functionality.

I've got enough information to investigate, thanks. I'll keep you informed.

Best regards
Hervé

**Comment by jmiller9591** [comment]
Hi Hervé

I confirm that the import I was trying previously does bring in the view correctly for me.  The upgrade process that I mentioned earlier seems to be still there (where I end up with previous and new plugin jar file in plugins folder)  

I get the following message when Archi restarts after downloading the new plugin from GitHub:

<img width="602" alt="screen shot 2018-11-13 at 7 07 54 am" src="https://user-images.githubusercontent.com/44744538/48417417-58cf1d80-e718-11e8-8980-b6cf74aa706d.png">

Thanks again so much for your help in supporting this plugin!

-John

**Comment by herve91** [comment]
Regarding the update error message, I effectively been told by other people. This is a false positive: in fact, the comparison between the downloaded vesion and the running version failes in some situations that I need to understand. But the good news is that the update works despite the error message.

As your import works now, I close this issue ... but do not be worried, I will adress the error message :-)

Best regards
Hervé

**Comment by jmiller9591** [comment]
Thanks Hervé.   Note that after the update there are 2 versions of the .jar file in the plugins directory (the older and newer one)  I have been just removing the older version and the message goes away.  Thanks again!

-John

**Comment by herve91** [comment]
Yes, I've read your post :-)

This seems to be specific to MAC as nobody told my this dupplication on Windows or Linux. This may be due to the fact that Archi fails to delete the old JAR file but unfortunately, I cannot trap the error as the JAR file cannot be removed while it is in use.

So the plugin asks Java to delete the file when Archi shuts down ... and obviously, when Archi shuts down, I cannot raise an alert if the file is not removed.

I'll continue to search on the net if someone has found a solution.

Please do not hesitate to create new cases should you discover other issues :-)
