### ISSUE TITLE
SQLException: Could not rollback with auto-commit set on

### ISSUE THREAD

**Issue by kaiserghetto** [archi-contribs/database-plugin#51]
Setting up Oracle 12c DB for the first time. I'm using v2.1.4 on Archi 4.3

I was able to connect to the database, but plugin fails to create tables by throwing this error on the log

ERROR  435:DBGui$4                                  - Cannot use this database.
java.sql.SQLException: Could not rollback with auto-commit set on

Any help would be appreaciated

**Comment by herve91** [comment]
Hi,

Could you please provide me with some more information ?

What were you doing when this exception was raised (initializing the database ? creating a new model ? updating an existing model ? ...)

Could you please also confirure the plugin's log level to "trace" on the preference page and send me the last lines including the complete exception stack trace and few lines above that I can investigate ?

Thanks and regards
Hervé

**Comment by kaiserghetto** [comment]
Also, just tested with a blank model, exactly the same problem.

**Comment by herve91** [comment]
Oracle does not allow to submit a rollback request when the connection is in auto commit while other database brands allow.

It will be fixed in the next release.

Best regards
Hervé
