### ISSUE TITLE
Cannot connect to oracle db using service name

### ISSUE THREAD

**Issue by v-yeung** [archi-contribs/database-plugin#57]
Cannot connect to an oracle database using a servicename, the syntax used for oracle only supports SID for database ID. Would be better if user is able to optionally specify the full jdbc connection string instead as this will allow for better integration with oracle (with all the other options that can be added to the string).

**Comment by herve91** [comment]
Fair enough ... will add it to next version.

**Comment by herve91** [comment]
added in version 2.1.9

Please confirm if it suits your needs.

Best regards
Hervé
