### ISSUE TITLE
Failed to count model's components

### ISSUE THREAD

**Issue by wwu206** [archi-contribs/database-plugin#59]
Hi
When I'm trying to export a model to SQL Server, right after choosing the  export model to database, it is raised a window with the error below:
"Failed to count model's components
NullPointerException"

The database is not visible and the only thing I can do is closing the import/export window.

Any ideas?

Best regards,
Rui

**Comment by herve91** [comment]
Hi,

My apologies for this late answer. I just tested again and it works for me.

Could you please provide more inforamtion about your configuration (version of Archi, version of the database plugin, version of SQL Server) and send me the end of the log file (please configure the logger in trace mode for that).

Best regards
Hervé
