### ISSUE TITLE
Passwords stored in plain text

### ISSUE THREAD

**Issue by pcmanning** [archi-contribs/database-plugin#61]
Noted that the plugin stores the username/password in plain text in the .prefs file.  In first instance these should be encrypted somehow.  However, for the various SQL Server options, it should be possible to pass the buck to Windows anyway?  Is the username/password even used?

**Comment by herve91** [comment]
The password is effectively stored in plain text, but the preference file is located in a folder accessible by the user only.

I could encrypt it, but as the algorithm needs to be reversible (because the password needs to be sent to the database during the connection phase) and as the algorithm will be public like all my code, then everybody will be able to easily decrypt the password.

Therefore this point has never been prioritized.

**Comment by pcmanning** [comment]
Given that the username/password is the Active Directory (and usually the same as the Azure AD creds due to sync), I would suggest you force a prompt rather than store it?  No idea of the behavior of the SQLJDBC pieces, but I'd guess if you don't provide a username/password in the string, then they'd trigger the OS to sort it out - which would usually result in SSO behavior since PC already logged in?

  So a change to the GUI to select OS SSO  (Single Sign On) or enable/disable save password?

**Comment by herve91** [comment]
If you already are connected to an Active Directory account, then this is the role of the sqljdbc_auth.dll file to transmit your credentials to the SQL Server database. In this case, there is no need to fill in your password in the plugin, thus no need to encrypt it :)

**Comment by pcmanning** [comment]
Will test with Azure AD next time I get access to confirm similar then.

**Comment by pcmanning** [comment]
Update - Azure connection requires a username/password - at least for my config - suspect if it was "Azure AD Joined" then this may disappear.  So request stands - option to prompt for username/password rather than store in plain text please?   Note that our Azure AD is about to go MFA, so have no idea of the affect on the plugin!

**Comment by herve91** [comment]
done

will be in the next plugin release
