### ISSUE TITLE
Unable to compile database-plugin using Eclipse 4.11 & Archi 4.5

### ISSUE THREAD

**Issue by eistomin** [archi-contribs/database-plugin#62]
I'm trying to create a jar using new Archi & Eclipse, plenty of errors in functions like getAll* :

getAllElements
getAllRelationships
getAllFolders
getAllViews
getAllViewObjects
getAllViewConnections

getAllImagePaths is the only one getAll* function declared in plugin, 
![2019-07-29_10-35](https://user-images.githubusercontent.com/16778577/62029977-a8913e80-b1ec-11e9-9e5c-853822d0d804.png)

Can you please confirm this?

**Comment by herve91** [comment]
On my side, I just have got errors on the model.getIdAdapter() method that dors not exist anymore.

On your side, did you install Lombok (https://projectlombok.org/) ?

You need to download and install the lombok.jar file on your desktop (the Eclipse folder is quite a good place for this) and add a line at the end of the eclipse ini file "-javaagent:<path>/lombok.jar"

**Comment by herve91** [comment]
I just uploaded an update to replace the model.getIDAdapter.getNewID() method by the UUIDFactory.createID() one.

The compilation works fine now on my desktop using Archi 4.5 / Eclipse 4.11 / OpenJDK 11.0.4

**Comment by eistomin** [comment]
@herve91 Thanks!
Can you please help with getAll* errors?

![1](https://user-images.githubusercontent.com/16778577/62043704-aee1e380-b209-11e9-847b-4209d2732468.png)

![2](https://user-images.githubusercontent.com/16778577/62043811-ff594100-b209-11e9-954a-d74e53065889.png)

**Comment by herve91** [comment]
As previously said, did you install Lombok (https://projectlombok.org/) ?

**Comment by eistomin** [comment]
Yes, "Help -> About" = "....Lombok v1.18.8 "Envious Ferret" is installed. https://projectlombok.org/"

**Comment by herve91** [comment]
So you need to understand why the methods are undefined. The methods are defined with Lombok (@Getter keyword) in the DBArchimateModel.java file.

![image](https://user-images.githubusercontent.com/9281982/62045809-9ae8b280-b206-11e9-8a4f-ba2231d918d3.png)

Please open the file and check if there are errors in this file. I do not have any on my desktop.

**Comment by eistomin** [comment]
Thanks! Closed
