### ISSUE TITLE
Conflicts while exporting to DB

### ISSUE THREAD

**Issue by dalman1** [archi-contribs/database-plugin#63]
With two different users trying to work collaboratively, we ran into an issue where there's two conflicts on the folders and we're unsure of how to resolve.  There doesn't appear to be a way to view (or ignore) the conflicts.

![Conflicts2](https://user-images.githubusercontent.com/48097014/62297335-04eb9c80-b43f-11e9-8608-14d602c968a6.png)

**Comment by herve91** [comment]
The process is described in the wiki and in my plugin's online help. To access it, you may click on the interrogation mark at the bottom left of the export window.

Here is a summary:

When you import a model from a database, my plugin keeps in memory its version.

When you export your model to the database, my plugin detects the conflicts if the version of the objects in the database increased since the import.

If you click in the "export button", a conflict resolution window will open and show a comparison of both versions (yours and your colleague's) and let you choose between 3 options:
1.  consider your version is the correct one and export it, replacing the version of your colleague
2. consider you' colleague's version is the correct one and import it, replacing your version in your model
3. do nothing, do not update the object in the database which means that the conflict will be raised again during the next export

Hope this helps.

**Comment by dalman1** [comment]
Thanks for a quick reply.  The help button on the plugin for some reason was blank (see below) for conflict resolution, and i must have missed it in the wiki.

![Help](https://user-images.githubusercontent.com/48097014/62302417-4df41e80-b448-11e9-8dbf-d18ec5799852.png)

However when he clicks "Export" he doesn't receive the conflict resolution popup, but instead receives the below a hard-error.  Could this be an issue on a Mac?  Should he save-off and try to have me try to upload from my PC?

![image](https://user-images.githubusercontent.com/48097014/62303851-e2f81700-b44a-11e9-9cb4-9a74a27e576e.png)

**Comment by herve91** [comment]
This error message should not happen. It indicates that the plugin does not find the source of a diagram connection.

What is weird is that it is not linked to the folders conflict at all.

Could you please go to the plugin configuration, and activate the log file in the "logger" tab. the simplest is to select "simple mode", then choose the "fatal" level.

Then, you need to reproduce the error and send me the log file by mail herve.jouin@gmail.com

Having the full log file makes the debug process easier for me but please note that doing so will show me your model (or at least part of it). So if your model is confidential, send me only the last lines that contain the full Java exception detail.

**Comment by herve91** [comment]
I received your log file. I'll investigate and let you know asap.

**Comment by dalman1** [comment]
I received a similar problem today.  Unfortunately I haven't yet turned logging on but, i'll step through what i saw.  I'll also email you a log.

1) I had been working on a model
2) Colleague made changes and uploaded
3) I then went to upload my model.
   a) I could see changes on my side and changes on the db.
   b) there were two folder conflicts and one view conflict
   c) the conflict resolution popup showed and identified what looks like renames on the folders or views
  d) i told it to ignore/not export the data to the DB
  e) it seemed to get stuck in an infinite loop trying to resolve the conflicts and kept prompting for conflict resolution and starting over etc...
  f) eventually i had to cancel out
  g) if i try and re-export to DB, i now have 4 conflicts on the folders and one in the view.  3 of the views don't appear to have any actual changes, one still a rename.
  e) same as e, in an infinite loop.
![Conflict3](https://user-images.githubusercontent.com/48097014/62562222-bda24900-b84e-11e9-843e-afc46ac6dbcc.png)
![Conflict4](https://user-images.githubusercontent.com/48097014/62562223-bda24900-b84e-11e9-8d32-552ca0bbc8f6.png)

**Comment by herve91** [comment]
In fact, the conflict resolution (so clicking on the "Do not export" button in your case) needs to be done for every conflict, unless you selected the "remember my choice" option.

**Comment by dalman1** [comment]
Yes, I told it not to export for every one.  afterwards, it appeared to perform the check again recalculating the counts and then the conflicts popup would re-appear.

**Comment by herve91** [comment]
You're right, your log file indicates that you clicked on the "do not export" button, but the information seems to be lost at some time.

I'm conducting some testing at this very moment and I'll let you know asap.

**Comment by herve91** [comment]
I rewrote the whole export method to fix this issue.

The next plugin version will include this fix.
