### ISSUE TITLE
"Relationships" -suffix on Neo4j

### ISSUE THREAD

**Issue by EeroHosi** [archi-contribs/database-plugin#64]
Now the relationships on Neo4j are containing the text "Relationships" -suffix. 
Could it be possible just leave the suffix text part "Relationships" away?
Then the diagram (on Neo4j) would be easier and analogous to ArchiMate, just showing e.g. "Serving", "Realization" etc. on the relationship line...

**Comment by herve91** [comment]
Done.

Will be in the next release
