### ISSUE TITLE
Plugin does not load with Archi 4.5.1 Portable/Windows10/64bit

### ISSUE THREAD

**Issue by jheitkoetter** [archi-contribs/database-plugin#65]
Just a minor issue, but changing from 4.4. to 4.5.1 portable edition on Windows 10/64bit the database-plugin is not loaded, i.e. does not "show up" in the import/export menu, while other plugins in the same "non-standard-path" directory are. ty

**Comment by herve91** [comment]
Archi 4.5 removes the method used to generate its internal objects IDs and replaced it by a brand new class. My database plugin references this method in order and therefore fails to load in Archi 4.5.

I'm currently working on a new version that will solve this issue.

**Comment by herve91** [comment]
new plugin version will be compliant with Archi 4.5.1
