### ISSUE TITLE
SQLServerException when importing components using ms-sql driver

### ISSUE THREAD

**Issue by grooveAtTic** [archi-contribs/database-plugin#66]
Driver: sqljdbc42.jar
Exception see attached screenshot:
![SQLServerException_NAME](https://user-images.githubusercontent.com/54706075/64177019-e83bed80-ce5e-11e9-87c7-89ba8f284b42.png)
Possible reason: Driver doesn't accept uppercase database column names:
File: v2\sources\src\org\archicontribs\database\GUI\DBGuiImportComponents.java
Line: 1852
`addOn += " AND version = (SELECT MAX(version) FROM "+this.selectedDatabase.getSchemaPrefix()+"elements WHERE id = e.id)";`
`addOn += " ORDER BY NAME";`
Also lines 1950 (commented out) and 2022

**Comment by herve91** [comment]
I never experienced any issue regarding uppercase/lowercase.

Could you please provide me the exact version of the SQL Server database you're using ?

**Comment by grooveAtTic** [comment]
Microsoft SQL Server Enterprise 13.0.5426.0

**Comment by herve91** [comment]
Thanks. 13.0.5426.0 is SQL Server 2016 SP2 cumulative patch 8.

I'll install it on a test machine and conduct some tests ...

**Comment by herve91** [comment]
SQL Server tablenames are effectively case sensitive.

I updated my code to have lowercase tablenames everywhere.

Will be in the ext plugin release.
