### ISSUE TITLE
SQLServerException when importing components using ms-sql driver number 2

### ISSUE THREAD

**Issue by grooveAtTic** [archi-contribs/database-plugin#67]
Driver: sqljdbc42.jar
Exception see attached screenshot:
![SQLServerException_RANK](https://user-images.githubusercontent.com/54706075/64178254-6ac5ac80-ce61-11e9-82f4-8e46450b0d43.png)
Possible reason: Driver doesn't accept uppercase database column names (ORDER BY RANK):
File: v2\sources\src\org\archicontribs\database\connection\DBDatabaseImportConnection.java
Line: 191
`try ( DBSelect resultProperties = new DBSelect(this.databaseEntry.getName(), this.connection, "SELECT name, value FROM "+this.schema+"properties WHERE parent_id = ? AND parent_version = ? ORDER BY RANK", id, version) ) { ...`
Also line 202

**Comment by herve91** [comment]
same issue as #66
