### ISSUE TITLE
ClassCastException DBResolveRelationshipsCommand cannot be cast to IDBImportCommand

### ISSUE THREAD

**Issue by grooveAtTic** [archi-contribs/database-plugin#68]
Importing components from database throws ClassCastException
![ClassCastException_IDBImportCommand](https://user-images.githubusercontent.com/54706075/64326479-53ee9980-cfca-11e9-9a5f-f8bfb6e31fb5.png)
in file v2/sources/src/org/archicontribs/database/GUI/DBGuiImportComponents.java line 2300:
`2298 Iterator<IDBImportCommand> iterator = undoRedoCommands.getCommands().iterator();`
`2299 while ( iterator.hasNext() ) {`
`2300    IDBImportCommand command = iterator.next();`
`2301`
`2302    if ( command.getImported() != null )`
`2303       imported.add(command.getImported());`
`2304 }`
Used JRE is AdoptOpenJDK jdk-8.0.222.10-hotspot as recommended by the Archi developers.
A possible fix might be:
`2298 Iterator<IDBCommand> iterator = undoRedoCommands.getCommands().iterator();`
`2299 while ( iterator.hasNext() ) {`
`2300    IDBCommand command = iterator.next();`
`2301`
`2302    if ( command instanceof IDBImportCommand )`
`2303       imported.add(((IDBImportCommand)command).getImported());`
`2304 }`

**Comment by herve91** [comment]
I never experienced this issue ... Which version of Archi and of the plugin are you using ?

**Comment by herve91** [comment]
I added your fix in my code.

Thanks
