### ISSUE TITLE
Archi database-plugin API

### ISSUE THREAD

**Issue by WatchTh1** [archi-contribs/database-plugin#69]
Greetings, dear Author! I'd like to propose to look over possibly usefull database API functions and precedures such as:
- Indexing common search fields as target_id, source_id and etc.
- Automated search index updates 
- Common search functions as "FInd and filter all object with relation type X to/from object Y in a model"
and so on.

I see it fit cause having such feature will greatly improve plugin's usability in many aspects as for example:
- Generating project documents 
- Integrating with knowledge bases
- Desicions verification and validation
- Model verification and validation 
and so on.

Please let me know if you see such functionality fit, and we can collaborate on this matter.

As about my intent:
1. As an system architect I'd like to have a toolset to support engeneering acivities based on system's engeneering principles
2. As an educator i'd like to have a simple tool to provide students with means to develop their skills in system modeling, system design, system verification and validation, desicion presentation.
3. As a system designer I'd like to have a tool to analyse request for change impact on a current or future system design.

About scope:  Small-medium projects with teams about 100-150 people at max.

Greatly appreciate your efforts and best regards, Alexander Luchkov.

**Comment by herve91** [comment]
Greetings Alexander,

I do not really understand what you're calling API. Are you searching for a way to import elements and relationships based on wider criterias (like "having a specific relationship with element X") ?

If your aim is to do impact analysis, I recommand you have a look to Neo4J database which can do it natively.

Best regards

**Comment by WatchTh1** [comment]
Beside impact analysys I'd like to have an option to generate a lot of project documentation by something like CI buildplan with LaTeX based tools in tasks, that's the thing for now.

Therefore I need for the enduser (such as technical writer for example)  a nice way to search through database to build complex reports, build traceablitiy matrices and so on.

For such task I'd like to have something like at least a bunch of SQL procedures, for example, which I'd be able to call via some driver, or to pass into other modeling modeling tools for data importing and analysys. If there is a more convinent way to do so I'd gladly apreciate if you would tell me.

In the future, i have some plans to test formal model verification based on built in metamodel to track flaws, inadequacies and so on after model is baselined, or commits are made. RDBE is a nice thing to store and sort data, but not for such things I think =)

**Comment by herve91** [comment]
Passing data from Archi to another tool won't be straight forward as both tools will not share the same metadata.

So, I believe you've got 4 options:
- export your model in Open Exchange format if your other tool supports it
- export your model to an SQL database if your other tool is able to query such database. The datamodel used by my plugin is described in the [database structure](https://github.com/archi-contribs/database-plugin/tree/master/v2/database%20structure) folder
- export your model in CSV if your other tool can import the CSV files generated by Archi
- create a jArchi script that exports your model using a specific file format that your other tool understands.
