### ISSUE TITLE
New model created in Archi 4 not exported to database

### ISSUE THREAD

**Issue by ZinovyevMaxim** [archi-contribs/database-plugin#7]
Hi,

Model created in Archi 3 opened in Archi4 exporting to database succesfully.
New model created in Archi 4 NOT exporting to database fail with error:
_An error occured while exporting your model to the database.
The transaction has been rolled back and the database is left unmodified.
MysqlDataTruncation : Data truncation: Data too long for column 'model' at row 1_

Archi 4, plugin 1.0.1

**Comment by herve91** [comment]
Hi,

You are right, the new beta releases of Archi 4 changed the IDs from a 8 bytes string to a 36 bytes string and my ID columns where sized 32 bytes long and need to be increased. In my local database, I set 50 bytes.

I will upload new sql scripts today.

Thanks for spotting this :)

Best regards
Hervé

**Comment by ZinovyevMaxim** [comment]
Sorry for long response for test.

Database  with length field "`folder` VARCHAR(50) NOT NULL" export not work.
Database with length field  "`folder` VARCHAR(100) NOT NULL" export succesfully.

I'm continue test. Thanks.

**Comment by ZinovyevMaxim** [comment]
Change  field length `parent` to  VARCHAR(100).

**Comment by ZinovyevMaxim** [comment]
1) Create 2 clear model
2) exported to database model.
3) Import shared model containing 2 models crerated on step 1
4) create View containing elements from 2 models and exported to database. Succesfuly
5) import shared failed:
_An error occured while importing the model from the database.
The model imported into Archi might be incomplete, please check below : 
Exception : importConnections() : cannot find relationship 4152986a-6c45-4410-812d-2ea700f1e691;6cd226ad;0.10_

Elements imported, Relations imported without link to elements, view Empty. Try delete whole model from database failed (Information window contains the text "model removed", but the model from the database is not deleted, and is contained in the list, import is unsuccessful).

**Comment by ZinovyevMaxim** [comment]
Archi 4.0, plugin 1.0.1

**Comment by herve91** [comment]
Hi,

Could you please check again with new release ?

thanks and regards
Hervé

**Comment by ZinovyevMaxim** [comment]
Hi!!

Download new release plugin and script for creation database MySQL.

1) Used for test example model "Archisurance"  export and import model sucessfully
2) Used for my model in Export type "Whole model" export fail
3) Used for my model in Export type "Elements and relationships only" export sucessfully

2017-03-31 19:13:15 INFO   128:DBPlugin                       - Initialising DatabasePlugin plugin ...
2017-03-31 19:13:45 FATAL  674:DBGuiExportModel$5             ┌ An error occured while exporting the components.
2017-03-31 19:13:45 FATAL  674:DBGuiExportModel$5             └ The transaction has been rolled back to leave the database in a coherent state. You may solve the issue and export again your components.
java.lang.ClassCastException: org.archicontribs.database.model.ArchimateModel cannot be cast to org.archicontribs.database.model.IDBMetadata
	at org.archicontribs.database.DBDatabase.exportProperties(DBDatabase.java:1206)
	at org.archicontribs.database.DBDatabase.exportModel(DBDatabase.java:1041)
	at org.archicontribs.database.GUI.DBGuiExportModel$5.run(DBGuiExportModel.java:652)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

**Comment by ZinovyevMaxim** [comment]
My version:
I'm used by in model grouping view in subfolder. First open model i'm see position "Delete" in subfolder context menu, after try export model to database i'm don't have position Delete in context menu for subfolder View (position inactive).

I assume that the problem in the export of subfolders in the "View"

**Comment by herve91** [comment]
Hi Maxim,

Could you please confirm the version of the plugin you downloaded ?

**Comment by ZinovyevMaxim** [comment]
Archi 4 Plugin 2alpha4

**Comment by herve91** [comment]
Hi Maxim,

I failed to reproduce but will do some more testing and will let you know.

Best regards
Hervé

**Comment by herve91** [comment]
Hi Maxim,

Could you please confirm that your issue has been solved with the latest version of my plugin ?

Thanks and regards
Hervé

**Comment by ZinovyevMaxim** [comment]
Hi Herve,

Im sorry for long time answer at your request.

You does perfect own job, she is excelent

My problem for import and export models from Archi3 fixed via new context menu position for model node "Convert old fashion IDs to Archi4".

I generator new bug)) In modal window for import and export model to database feature "Filter" work not correct. When me writes request for choose model, filter founds models and adding to end list. If i correct understand functionality, then list must replace to founded list.

Thank for good job!

Config
Archi4.0
Plugin 2.0.6

**Comment by herve91** [comment]
Hi Maxim,

I just understood what you meant in your last message. When you convert the IDs from Archi 3 to Archi 4 format, it also converts the model ID. From a database point of view, your model is therefore a new one.

I understand that it may be not what you expected, but this is normal behaviour.

Best regards
Hervé
