### ISSUE TITLE
Error on Export/Import

### ISSUE THREAD

**Issue by dalman1** [archi-contribs/database-plugin#70]
Thanks for the update addressing my previous import/export issues.  I now have two issues, one of which may just be cosmetic and non-breaking, the second is breaking.

1) Importing and Exporting appears to work correctly, however, for some reason when exporting back to the DB, the counts are doubled (see screenshots ExportBefore and ExportAfter).  Before is before i click the export button, and after, after.  The counts for some reason appear to double.  Subsequent imports appear to work without issue.

![ExportBefore](https://user-images.githubusercontent.com/48097014/66773564-495ad600-ee8d-11e9-968c-b0fe079aa82d.png)
![ExportAfter](https://user-images.githubusercontent.com/48097014/66773565-495ad600-ee8d-11e9-86c6-b0db0298151c.png)

2) If i export after moving a folder to another folder it appears to break.  I can no longer import the data.

![FolderMoveImportError](https://user-images.githubusercontent.com/48097014/66773563-495ad600-ee8d-11e9-9b18-a69fd67fcb4e.png)

Thanks, and if need be, I can probably send a copy of the DB (pre error) if that helps.
Dan

**Comment by herve91** [comment]
Hi Dan,

I effectively observed this during my dev, but I thought I solved it. I'll do more tests and let you know ASAP.

Thanks
Hervé

**Comment by herve91** [comment]
I did some tests and I effectively reproduced the error on the number of components in the model.

But I cannot reproduce the import error after moving a folder in another one.

Could you please provide me a step by step procedure that I could follow to reproduce it ?

Thanks
Hervé

**Comment by dalman1** [comment]
I've added a zip file which follows the following:
1) Shows current view folder structure
2) Create a new root folder under "\Views" 
3) Move the subfolder "\Data\OMS" which has subfolders and views to the newly created folder.
4) Shows new folder state
5) Pre Export
6) Export
7) After closing the model and trying to re-import, receives the import error regarding bad counts.

[ImportError.zip](https://github.com/archi-contribs/database-plugin/files/3734837/ImportError.zip)

**Comment by herve91** [comment]
I just conducted some tests, using Archi 4.5.1 (plugin version 2.2 and a SQLite database), and I followed your description and screenshots.

- Open a medium size Archimate file (243 elements, 460 relationships, 22 views)

- Update the views folder structure to be like yours
![image](https://user-images.githubusercontent.com/9281982/67092969-e2049500-f1b0-11e9-8dcb-c106f8b6a4f5.png)

- Export the model to the database (creating version 1 of the model) -> I reproduced the double counting of the model's components
![image](https://user-images.githubusercontent.com/9281982/67093160-4f182a80-f1b1-11e9-808f-5e4f6b1882b9.png)

- Create a new folder and move the "Functions" folder that has got a subfolder and several views to this new folder
![image](https://user-images.githubusercontent.com/9281982/67093218-6b1bcc00-f1b1-11e9-9d3a-d2af9c5d7f77.png)

- Export the model to the database (creating version 2 of the model)
![image](https://user-images.githubusercontent.com/9281982/67093243-766ef780-f1b1-11e9-8440-67c393f7bdbd.png)

- Close the model
- Import the model from the database

 but did not experienced any issue when I imported back the model from the database.
![image](https://user-images.githubusercontent.com/9281982/67093303-9d2d2e00-f1b1-11e9-8fb6-c0ee3d7a1f4b.png)

Best regards
Hervé

**Comment by dalman1** [comment]
I'll email you a scrubbed version of the model that i can consistently replicate with.

Thanks,
Dan

**Comment by dalman1** [comment]
Correction, it appears to corrupt every time i just create a folder in views, not when i move the folders around.

**Comment by dalman1** [comment]
I did some tracing and the error appears to be related to duplications in the views_connections_in_view table.  See below screenshots of before and after adding a single folder and importing/exporting.

Before:
![Before](https://user-images.githubusercontent.com/48097014/67325883-d3391d80-f4e3-11e9-8deb-fad6e6941ceb.png)

After exporting a single change of adding a folder:
![After](https://user-images.githubusercontent.com/48097014/67325922-e0560c80-f4e3-11e9-909a-f8fd95b586f8.png)

**Comment by herve91** [comment]
I received your database backup by email. I'll conduct some tests.

It may be related to MS SQL Server and I failed to reproduce it with SQLite.

**Comment by herve91** [comment]
Did you renamed your model's objects voluntarily, or is there an issue with my restore ?
![image](https://user-images.githubusercontent.com/9281982/67415769-e7ede200-f5c5-11e9-8edd-5d7e22ba87eb.png)

**Comment by dalman1** [comment]
No, thats me, I scrubbed the names with new guids.

**Comment by herve91** [comment]
ok, no problem. I just wondered if I did something wrong.

Here is the state of my investigations.

When I move view folders into subfolders into your database, then I succeed to reproduce your issue.

When I import your model and export it to a brand new database, then move view folders into subfolders and export it to the new database again, then I fail to reproduce your issue.

This is quite weird. I need to investigate your database in depth.

**Comment by dalman1** [comment]
I created an empty Archi DB and was able to export to there.

Afterward, i imported it, and created a new root folder under views then successfully exported back to the DB.

I then was able to import this DB back into Archi where I moved a folder and re-exported back to my newly created DB.

However, when i tried to import into, it failed again.

![CleanDBError](https://user-images.githubusercontent.com/48097014/67500021-0dbfc900-f650-11e9-8dbf-eae1adf5530b.png)

**Comment by dalman1** [comment]
fyi, i tested again with 2.1.11, and this does not appear to happen.  We'll rollback to that version for now.

**Comment by herve91** [comment]
I've finally found what happens.

I do not know if you're interested in the cause, but I write it here at least for reference.

When I export the model to the database, I do not export components that have not been updated. The objects that are effectively exported to the database are counted in the 'new' and 'updated' columns of the export window, the other objects are already in the database so I just need to register them as being part of the model (that's the count in the 'total' column during the export).
![image](https://user-images.githubusercontent.com/9281982/67599554-99307b80-f770-11e9-8902-df76d5b7f400.png)

For objects and connections that are part of a view do not need to be referenced again when the view is not exported, as this conducts to a double reference, and thus to import them twice.

Thank you very much for sharing your model with me (even scrubbed), and for the procedure that highlighted the issue.

I'll submit a new version before the end of the weekend that fixes this double reference, and with some admin tools to fix the databases that contain such double references.
