### ISSUE TITLE
SQL Performance Suggestion

### ISSUE THREAD

**Issue by dalman1** [archi-contribs/database-plugin#71]
Not a bug, but a low priority suggestion for SQL Server performance.  

While watching the counts for elements slowly increment and i was curious if it could be quicker.  We currently have 494 elements with 40 properties per element.  

I performed a trace and each select appeared to take 4ms, and with a lot of elements and properties it adds up.  I noticed that the parameterized query is using nvarchar for the parent_id etc., but the field is actually a varchar.  If i keep the datatypes the same, it drops the runtime down from 4ms to <1ms.  Because of the datatype difference it forces a conversion to match the unicode/non-unicode data.

Attached are some executionplans and trace results.  The suggestion would be one of two, basically keeping the data types the same.

1. If when drafting the parameterized query you can keep parent_id (or any varchar) to be varchar instead of it becoming nvarchar.
2. Update the datatypes on the Archi database to be always nvarchar.

Thanks,
Dan

![CurrentCost](https://user-images.githubusercontent.com/48097014/67021858-4d296b00-f0ce-11e9-857c-d786f040fc16.png)
![TargetCost](https://user-images.githubusercontent.com/48097014/67021859-4d296b00-f0ce-11e9-8bdd-892c0f32da16.png)
![Trace](https://user-images.githubusercontent.com/48097014/67021860-4d296b00-f0ce-11e9-9148-29bf13f5a1c9.png)

**Comment by herve91** [comment]
Hi,

Thanks for reporting this issue.

For MS SQL Server databases, I effectively define IDs as `varchar(50)`. When I construct the SQL statement that gets IDs from the database, I request a varchar, not a nvarchar.
> void java.sql.PreparedStatement.setString(int parameterIndex, String x) throws SQLException
>
> Sets the designated parameter to the given Java String value.The driver converts this to an SQL VARCHAR or LONGVARCHAR value (depending on the argument's size relative to the driver's limits on VARCHAR values) when it sends it to the database.
>
> Parameters:
> parameterIndex the first parameter is 1, the second is 2, ...
> x the parameter value
>
> Throws:
> SQLException - if parameterIndex does not correspond to a parametermarker in the SQL statement; if a database access error occurs or this method is called on a closed PreparedStatement

So I do not know how to fix it :(

**Comment by WatchTh1** [comment]
To speedup performance I personaly created additional indexes on every text r uui field in the database.  Results are satisfying.

I'm using PostgreSQL, my  model contains about 12000 elements and relations in total, changes are about 1-2 thousands per version. Builgin a complex report (for example composition tree with attributes for given concept) takes about 2-3 seconds. Report contains up to 50 records.

Maybe to include additional indexes in DB Schema would be nice to speedup analysis tasks.

**Comment by herve91** [comment]
Could you please open a separated thread for the index stuff ...

I will check with you the best indexes to create.

Thanks.

**Comment by herve91** [comment]
I close this issue as I do not know how to fix it.
