### ISSUE TITLE
SQLException: The server time zone value 'AKST' is unrecognized...

### ISSUE THREAD

**Issue by sonear** [archi-contribs/database-plugin#72]
My server is in alaska and as such, runs in AKST or AKDT depending on time of year. The previous version of the plugin 2.1.11 did not care about this setting but now 2.2 fails to connect with the error below. I researched forums and settled on changing my connection string to set serverTimezone.

My connection String now requires "&serverTimezone=UTC" in order to connect.

(assumes expert mode button is checked in preferences)
jdbc:mysql://host.example.com:3306/DBNAME?serverTimezone=UTC

Full Error Attached:
![Database_import_export_plugin_vorg_archicontribs_database_DBPluginVersion_7026b7ee_and_Database_import_export_plugin_vorg_archicontribs_database_DBPluginVersion_7026b7ee_-_Export_model-2](https://user-images.githubusercontent.com/5515125/67347004-37141400-f4ed-11e9-8498-49533d860800.png)

ALSO... please note typo in the word "specific". In the error message, it is spelled "specifc"

Thanks

**Comment by herve91** [comment]
The error message is generated by the JDBC driver. So you may tell MySQL about the typo :-)

The timezone error in timestamps is referenced in MySQL. When a fix is provided, I'll update the JDBC driver.

**Comment by sonear** [comment]
So I found this oldie moldy bug on mysql site.

Seems to be exactly what I'm experiencing. Based on comments and age of this issue I'm not optimistic of it ever being addressed but I'll share the link here for others to commiserate with

Thanks

Scotty

https://bugs.mysql.com/bug.php?id=90813

**Comment by herve91** [comment]
Plugin version 2.2.1 will rollback the MySQL driver to version 5.1.48 to bypass the timezone bug.

I'll upgrade back to driver to version 8 when the timezone bug is solved.
