### ISSUE TITLE
Archi plugin installer

### ISSUE THREAD

**Issue by WatchTh1** [archi-contribs/database-plugin#74]
Could you please make an Archi plugin installer release for version 2.2.1?
Seems like it's simple as zip file with *jar binary and "magic file" named archi-plugin with contents:

`Magic file to signify this is an Archi plug-in bundle.`

And named with extension _archiplugin_

**Comment by herve91** [comment]
Archi 4.6 also accept zip files, as Archi 4.5 did. Just select "*.zip" in the plugin installation window.

![image](https://user-images.githubusercontent.com/9281982/68674362-06f0eb80-0556-11ea-8bd8-187431faac43.png)

**Comment by WatchTh1** [comment]
I can upload it here, would you ppublish it ?

**Comment by herve91** [comment]
I do not understand ... it's already published [org.archicontribs.database_2.2.1.zip](https://github.com/archi-contribs/database-plugin/blob/master/v2/org.archicontribs.database_2.2.1.zip)

**Comment by WatchTh1** [comment]
Didn't notice this thing, sorry. Thought it would be nice if it would be
published at https://github.com/archi-contribs/database-plugin/releases.

Best regards, Alexander Luchkov

вт, 12 нояб. 2019 г. в 19:55, Hervé Jouin <notifications@github.com>:
