### ISSUE TITLE
[feature] Additional index stuff

### ISSUE THREAD

**Issue by WatchTh1** [archi-contribs/database-plugin#75]
General thread to build up database indexes for speeding up query performance.

Referenced from 
https://github.com/archi-contribs/database-plugin/issues/71#issuecomment-553134219

**Comment by herve91** [comment]
I will add indexes in the next release.

**Comment by WatchTh1** [comment]
Maybe this is not a best way, but I'm currently using following function to reindex model database after update on my PgSQL RDBMS: 

`CREATE OR REPLACE FUNCTION full_reindex()
	returns varchar as
$func$
DECLARE
	_idx_rec 				record;
	_idx_table_name 		varchar;
	_idx_column_name 		varchar;
	_idx_name				varchar;
	_idx_cmd				text;
	counter 				int DEFAULT 0;
 
BEGIN 
	for _idx_rec 	in
					select 
						is_t.table_name as table_name
						, is_c.column_name as column_name
					from information_schema."tables" as is_t 
						join information_schema."columns" as is_c on
						is_t.table_name = is_c.table_name
					where
						is_t.table_type = 'BASE TABLE'
						and is_t.table_schema = 'public'
						and is_c.table_schema = 'public'
						and is_c.data_type in('character varying', 'text', 'timestamp without time zone')
	loop
			_idx_table_name := _idx_rec.table_name;
			_idx_column_name := _idx_rec.column_name;
			_idx_name := concat(_idx_table_name,'_',_idx_column_name,'_idx');
			_idx_cmd := format ('CREATE INDEX IF NOT EXISTS %1$I on public.%2$s USING btree (%3$I);', 
								_idx_name, 
								_idx_table_name, 
								_idx_column_name);
		
		raise notice 'IDX CMD: % ', _idx_cmd;
		execute format ('DROP INDEX IF EXISTS %1$I;',_idx_name);
		execute format ('CREATE INDEX IF NOT EXISTS %1$I on public.%2$s USING btree (%3$I);', 
								_idx_name, 
								_idx_table_name, 
								_idx_column_name);
		counter := counter+1;
	end loop;
	
	return concat('Indexes processed: ', counter::varchar);
	
END; 
$func$
language plpgsql;`

**Comment by herve91** [comment]
Thanks for this, but I need to stick as close as possible to SQL standard as I need to create the same stuff for postgresql, mysql, oracle, sql server, and sqlite.

**Comment by herve91** [comment]
On which columns do you create your indexes ?

Let's talk about the elements table for instance. I've got two kind of requests on this table:
- SELECT * FROM elements WHERE id = ? AND version = ?
- SELECT MAX(version) FROM elements WHERE id = ?

I declared a primary key on (id, version) so the corresponding index should be used for both requests. I do not see which index would improve performances on this specific table.

**Comment by WatchTh1** [comment]
Well, multicolumn indexes are most usefull if you know typical requests and have a need to speed them up more when using single column indexes. They will help when you have tons of queries using defined column set.

I have 13 single column indexes on elements table, and 1 multicolumn index. Here they are

|schemaname|tablename|indexname|tablespace|indexdef|
|----------|---------|---------|----------|--------|
|public|elements|elements_checksum_idx||CREATE INDEX elements_checksum_idx ON public.elements USING btree (checksum)|
|public|elements|elements_deleted_on_idx||CREATE INDEX elements_deleted_on_idx ON public.elements USING btree (deleted_on)|
|public|elements|elements_deleted_by_idx||CREATE INDEX elements_deleted_by_idx ON public.elements USING btree (deleted_by)|
|public|elements|elements_checkedin_on_idx||CREATE INDEX elements_checkedin_on_idx ON public.elements USING btree (checkedin_on)|
|public|elements|elements_checkedin_by_idx||CREATE INDEX elements_checkedin_by_idx ON public.elements USING btree (checkedin_by)|
|public|elements|elements_created_on_idx||CREATE INDEX elements_created_on_idx ON public.elements USING btree (created_on)|
|public|elements|elements_created_by_idx||CREATE INDEX elements_created_by_idx ON public.elements USING btree (created_by)|
|public|elements|elements_type_idx||CREATE INDEX elements_type_idx ON public.elements USING btree (type)|
|public|elements|elements_documentation_idx||CREATE INDEX elements_documentation_idx ON public.elements USING btree (documentation)|
|public|elements|elements_name_idx||CREATE INDEX elements_name_idx ON public.elements USING btree (name)|
|public|elements|elements_class_idx||CREATE INDEX elements_class_idx ON public.elements USING btree (class)|
|public|elements|elements_id_idx||CREATE INDEX elements_id_idx ON public.elements USING btree (id)|
|public|elements|elements_data_idx||CREATE INDEX elements_data_idx ON public.elements USING btree (name, documentation, created_on, created_by, class)|
|public|elements|elements_pkey||CREATE UNIQUE INDEX elements_pkey ON public.elements USING btree (id, version)|

**Comment by WatchTh1** [comment]
> postgresql, mysql, oracle, sql server, and sqlite.

Harsh you go) I don't think query optimization is possible for every of them simultaneously. I think the optimal way to do things, is to provide single column indexes for everything that could be searched or compared, except **bytea** fields.

**Comment by herve91** [comment]
I do not understand why you create so many indexes.

The only columns I have in WHERE clause are id and version.

**Comment by WatchTh1** [comment]
I have a lot of other queries, which are using this indexes.
They are not for internal plugin functionality.

**Comment by herve91** [comment]
fair enough ... but when you opened this thread, you were thinking about improving performance of the plugin, weren't you ?

In that perspective, what indexes do you suggest ?

**Comment by WatchTh1** [comment]
> fair enough ... but when you opened this thread, you were thinking about improving performance of the plugin, weren't you ?
> 
> In that perspective, what indexes do you suggest ?

I've started this thread having in mind following stories:

1. As end user I'd like plugin to create and manage indexes for queries I develop on the database out of the box, to spend lesser time to define indexes and reindex triggers for exact database instance everytime.

2. As end user I'd like Archi to speed up database export task on large models.

As possible solutions I could think:
For the 1'st one - maybe currently it could be made as addtitional scripts for those who need them.

For the 2'nd one:
I suppose (as hipothesis) there is a way to shift part of workload done merging model versions to RDBMS (for example to prepare better datasets for plugin to compare localy). 

Some rational:
Typicaly in enterprise environment end user workstation has less resources than RDBMS Server. Additionaly user's workstationruns a lot of software beside Archi. So transferring workload to RDBMS may significantly improve performance in general for production needs.

Solution:
To define stored functions and procedures helping Archi to prepare datasets for analysis. This will require to have additional indexes for fields to support analysis task on RDBMS side.

**Comment by herve91** [comment]
Ok, they're are two parts here ...

1. regarding indexes for your specific requests have to be managed by you. I'm sorry but I cannot developp specific stuff for individual needs.

2. I fully agree that the export procedure performance must be improved. Unfortunately, I manage several database brands: Oracle, Microsoft SQL Server, PostGreSQL, MySQL, SQLight at the moment (and I also have got in my backlog to add the support of additional brands).

It's already quite complicated to arrange for the specificity of all of them. Adding procedures or functions in the database will add complexity that I'm not ready to support.

So I need to find another way and I'm convinced that improving my algorithm is the best solution.

**Comment by WatchTh1** [comment]
> 1. regarding indexes for your specific requests have to be managed by you. I'm sorry but I cannot developp specific stuff for individual needs.

Ok, that's not a problem.

> 2. I fully agree that the export procedure performance must be improved. Unfortunately, I manage several database brands: Oracle, Microsoft SQL Server, PostGreSQL, MySQL, SQLight at the moment (and I also have got in my backlog to add the support of additional brands).
> So I need to find another way and I'm convinced that improving my algorithm is the best solution.

I have to notice, that DB Tool is VERY USEFULL! It's one of the best things I could find for my purposes. The most important thing it provides, as I see:

As end user I'm available to analyse my architecture by quering database  to generate data marts for different stakeholders. (diagrams, charts, graphs, tables, analytics, views, etc.)

I agree that this is quite DB dependent and improvements in this direction will affect DB compatiility.
As I'm interested in this plugin, I'd like to propose following solution:

Incapsulate typical SQL queries into stored procedures you could call "select * from get_all_elements_from_db()" inside java code with predictable result. AFAIK this syntax is not DB dependent.

This would provide more flexibility to end users, so they can modify database schema independently, leaving algorythms on your side as you'd like.

If you'd like I can create functions for DB engines you need. But i need a list of queries you are currently using.

**Comment by herve91** [comment]
> This would provide more flexibility to end users, so they can modify database schema independently, leaving algorythms on your side as you'd like.

Wow ... that may make your life much easier, but it will make mine much harder. I believe you may not foresee the difficulty to support databases where I do not control the database schema.

I'm sorry, but I won't go this way.

**Comment by WatchTh1** [comment]
> Wow ... that may make your life much easier, but it will make mine much harder. I believe you may not foresee the difficulty to support databases where I do not control the database schema.
> 
> I'm sorry, but I won't go this way.

This is predictable, I'd also would like suggest to make SQL functions to update data, to make your life easier as well while developing java code.

**Comment by herve91** [comment]
plugin version 2.2.2 has got big performance improvement, even if I did not add indexes nor create DB functions
