### ISSUE TITLE
Support for Archimate 3.1 (ValueStream)

### ISSUE THREAD

**Issue by sonear** [archi-contribs/database-plugin#76]
Hello

As you know, Archimate 3.1 just release this month and includes a new entity named ValueStream. I have been testing the Archi 4.6 Beta version which is intended to be the supported version that formally includes Archimate 3.1 standard.

As part of my testing I wanted to see if the database plugin would still work. It appears that the change to the metamodel is an issue for 2.2.1 (not surprising since ValueStream is new).

What is your roadmap to support for the 3.1 MetaModel? 

Thanks!

Here is the error I get when exporting to database
![Database_import_export_plugin_v2_2_1_and_Database_import_export_plugin_v2_2_1_-_Export_model](https://user-images.githubusercontent.com/5515125/68909070-9d114700-06f9-11ea-8294-ab39b5c50623.png)

**Comment by herve91** [comment]
Hi Scott,

I'm currently working on a solution to avoid maintaining 2 versions of my plugin, one for Archi 4.5 and another one for Archi 4.6 ...

To achieve this, I need to rewrite some classes ...

I'm doing my best to release an Archi 4.6 compatible plugin early December.

Best regards
Hervé

searching for a solution to keep a single plugin that is working for both Archi 4.5 and Archi 4.6.

If I fail, I'll have to maintain 2 versions

**Comment by WatchTh1** [comment]
I have to notice, that Archimate 3.1 changed available relationship set. And thus migration from Archi 4.5 to 4.6 models are NOT trivial. For example outbound *flow* relation from *Artifact* is not supported.

This could be an issue, if someone would like to migrade a long stored story database to a new version. 

As a solution I'd propose to have a definition of Archimate version for selected model, but I personaly think it has to be done in main Archi tool. This improvement should prevent plugin authors to support multiple versions of Archi without additional workload.

**Comment by herve91** [comment]
The plugin is importing the model as it is in the database, even if the relationships are not allowed by the Archimate norm.

Thus, a flow relationship from an artifact that has been added in a model using Archi 4.5 will be imported in the model without error message.

Please note that this is the same behaviour than if you open a .archimate file that contains such relationship.

**Comment by jbsarrodie** [comment]
Migrating models to a new ArchiMate version as never been trivial, but this time, only a handful of relationships have been removed. The example you provided made no sens anyway so this must have been a mistake .

The easiest way to migrate is to run a jArchi script that checks relationships and convert those which are no more allowed to association.

If you're not in a hurry then wait a bit as I'm planning to release such script soon.

**Comment by herve91** [comment]
Thanks JB :)

**Comment by herve91** [comment]
new version 2.2.2 is compliant with Archi 4.6

**Comment by sonear** [comment]
Thanks!
