### ISSUE TITLE
Merge Mode

### ISSUE THREAD

**Issue by dalman1** [archi-contribs/database-plugin#77]
Using archi collaboratively the one area that concerns me is when two people are creating/updating their individual models.

When person A checks in, then 5 minutes later person B checks in, appears that the plugin considers person A's data has been deleted, and its no longer in the newest version.  Could there be a "merge" where no data is actually deleted?

If it supposed to already merge, i'll do more testing and see where/how this happens.

Thanks,
Dan

**Comment by herve91** [comment]
Hi Dan,

In fact, the plugin should delete person B's objects only if person A deleted objects ... else the objects are merged as shown in the following diagram:

![image](https://user-images.githubusercontent.com/9281982/69563197-eb9fca80-0fb0-11ea-86b1-627f86f32e9b.png)

Best regards
Hervé

**Comment by herve91** [comment]
Hi Dan,

You did not answered ... Is it the behaviour you expected ?

**Comment by herve91** [comment]
close as no answer
