### ISSUE TITLE
v2.2.2: Export to Neo4j broken?

### ISSUE THREAD

**Issue by normenmueller** [archi-contribs/database-plugin#78]
Trying via bolt, http, or https none approach works. However, checking the connection works just fine, but executing export gives in case of bolt

![image](https://user-images.githubusercontent.com/428576/70180507-76cf3d80-16e0-11ea-8043-5fd7bb46aec0.png)

although the previous connection check worked. In case of http

![image](https://user-images.githubusercontent.com/428576/70180610-a716dc00-16e0-11ea-84cc-7dc5e98d65cb.png)

and in case of https

![image](https://user-images.githubusercontent.com/428576/70180681-cb72b880-16e0-11ea-9d05-970adc5aa58e.png)

Any ideas?

**Comment by herve91** [comment]
Did it work with previous version of the plugin or is it your first export to Neo4J ?

version 2.2 of the plugin did update the Neo4J library but 2.2.1 and 2.2.2 did not change anything regarding Neo4J.

**Comment by normenmueller** [comment]
This is the first time I'm using Archi & this plugin. Sorry, have no previous experiences.

**Comment by herve91** [comment]
don't be sorry :-) it was just to check if the issue was introduced with the specific version 2.2.2 of the plugin ...

I must admin that I do not use Neo4J a lot ... I'll do some tests and let you know

**Comment by xmayeur** [comment]
Actually, it behaves like the user's credentials are not passed through when interacting with the data base.

**Comment by herve91** [comment]
I've found an issue related to credentials with Neo4J database.

Will be fixed in next release.

(I'm waiting for your confirmation before closing this issue)

**Comment by normenmueller** [comment]
> Will be fixed in next release.

Ping me when done. I'll test!

**Comment by herve91** [comment]
Hi Normen,

Version 2.2.3 fixed the issue on my desktop but not on Xavier's. I'm in touch with him by mail and I'll let you know when it will be fixed for all the situations.

Regards
Hervé

**Comment by normenmueller** [comment]
Hi @herve91! Any news? BR, /nm

**Comment by herve91** [comment]
fixed earlier this year.
