### ISSUE TITLE
Neo4J v2.2.2 Bug report - I think

### ISSUE THREAD

**Issue by BPMConsulting** [archi-contribs/database-plugin#79]
I have problem with connecting to Neo4j DB in v2,2,2. This is the first time I try neo4j.

using this setting:
![image](https://user-images.githubusercontent.com/43631625/70267596-0c310700-179f-11ea-95a3-0a0b19a44bca.png)

It checks fine, but then a few seconds later, I'll get:
![image](https://user-images.githubusercontent.com/43631625/70267464-cecc7980-179e-11ea-8df8-fe1dc5cfda93.png)
No action in the neo4j log either.

Changing to Expert Mode:
![image](https://user-images.githubusercontent.com/43631625/70267723-4d291b80-179f-11ea-87ef-a5dc06a25d54.png)
.. and "Check".  I'll get the same error message as above . Still no action in the Neo4j log.

Note the JDBC string. There is an <0> added behind the colon. I remove the zero and add the Bolt <7687>.
![image](https://user-images.githubusercontent.com/43631625/70267950-c6c10980-179f-11ea-9ad2-c05516cd12be.png)
The config checks fine but this time after trying to connect to DB I get
![image](https://user-images.githubusercontent.com/43631625/70268377-a0e83480-17a0-11ea-8543-e08e124b4f57.png)
The difference is that this time I can see that Archi is connecting against Neo4j in the neo4j log. 
![image](https://user-images.githubusercontent.com/43631625/70268485-d856e100-17a0-11ea-9f30-0f81c9071b63.png)

So there is hope with this workaround. But this is as far as I get with my limited IT experience. I hope my little workaround can help somebody with technical skills to figure out how to solve the issue.

**Comment by herve91** [comment]
Hi,

Thanks for reporting this issue. I'll conduct some more testing and let you know ASAP.

Best regards
Hervé

**Comment by herve91** [comment]
I've found the issue.

It will be fixed in the next release.

(I'm waiting for your confirmation before closing this issue)

**Comment by herve91** [comment]
Sorry for the delay, I'm very busy at the moment ...

I just sent the version 2.2.4 that fixes this issue.

Could you please confirm ?

**Comment by BPMConsulting** [comment]
Hi Herve,

 

Not to worry, we had a work around using CSV files.

 

I have downloaded and updated the new version, but I’m at a client site all day behind firewalls, so I will try to have a look at it tomorrow when I’m back in my normal environment at my office.

 

And thank you so much for your contribution to Archi. You truly make a difference for myself and my clients.

 

Regards, Thomas

**Comment by herve91** [comment]
Thanks for your kind message. You're more than welcome.

**Comment by adisD** [comment]
Hi Herve, 

database plugin 2.2.4 seems still to be having login/network issues with neo4j.
I do run everything locally on Mac machine. Archi is vresion 4.6 and Neo4j is 4.0.2.

regards, Adis

**Comment by herve91** [comment]
Please try plugin 2.2.5, I updated the Neo4J driver to be compliant with Neo4J version 4. It work on my test VM.
![image](https://user-images.githubusercontent.com/9281982/80319157-2da69400-880f-11ea-8c01-5c2a6cb388da.png)

**Comment by herve91** [comment]
Could you please confirm your issue is solved ?
