### ISSUE TITLE
Get History of DataObject ... fails

### ISSUE THREAD

**Issue by xmayeur** [archi-contribs/database-plugin#80]
Hello,

When selecting an object in a view, and right-clicking on "Get History...", the operation fails and reports:
```
Failed to search component versions in the database.
MySLQNonTrancientConnectionException: No operation allowed after connection closed.

```

The behavior is the same when using MySQL or SLQLite databases

**Comment by herve91** [comment]
Hi,

This error has already been reported and corrected. It will be fixed in the next release (before the end of the week).

Best regards
Hervé

**Comment by xmayeur** [comment]
Super
