### ISSUE TITLE
Conflict remains after corrective actions

### ISSUE THREAD

**Issue by xmayeur** [archi-contribs/database-plugin#81]
**Conflict resolution does not work.**

1. using MySQL
When a conflict is detected, the attached form proposes corrective actions (do nothing, export to model, import from database)
When clicking the one the selected action button, the list of conflicts decreases until empty, then when the last conflict is resolved, the original list of conflict pops up again and it is impossible the close the form unless aborting the operation.

2. Using SQLite
Pressing on the actions buttons does something (too quick to see what happen) but the list of conflict remains the same. Cancel is the only option to exit the form.

![archi-db-conflict](https://user-images.githubusercontent.com/15686120/70507727-3bdc6800-1b2d-11ea-9e8c-559f9062fb78.PNG)

**Comment by herve91** [comment]
Hi,

To ease this bug resolution, could you please switch the plugin's logger mode to "trace" and send me the generated log file by email (herve.jouin@gmail.com).

Please note that doing so will give me informations on your model, so please do not send it if your model is confidential. If this is the case, please check the log file content and send me any line with ERROR or FATAL status and all the Java exceptions if any.

Thanks
Hervé

**Comment by herve91** [comment]
close as no information provided to investigate
