### ISSUE TITLE
Upgraded DB/Lost Properties

### ISSUE THREAD

**Issue by dalman1** [archi-contribs/database-plugin#83]
Not critical for me, but when the upgrade happened it added the `properties `and `features `columns to the `elements `table.  It looks like by default it left the value as `NULL`.  The issue arose when i exported back to the DB.  Oddly, it said there 450 elements updated, which i disregarded as a side-effect of the plugin upgrade.  I later noticed later that after the next import there were no properties on my elements anymore.

I fixed this by manually updating the `properties `table to use the correct parent version and updating the the `elements.properties` column with the count.

**Comment by herve91** [comment]
I create the properties and features columns with a default value of 1, not null. What database brand are your using ?

**Comment by dalman1** [comment]
SQL Server.  I'll retest from a previous backup and perform a trace.

Should the value be 1 or the count?  I want sure, so I guessed count.

**Comment by herve91** [comment]
The export procedure stores the count as it is not costly and that the information might be useful one day.

But the import procedure does only a simple check:

- equals to zero means no SQL request to import properties (or features). If properties (or features) do exist, then they are not imported.
- different from zero means it runs a SQL request to get properties (or features). If properties (or features) do exist, then they are imported, if not, the SQL request just return an empty answer and no issue is raised (that was the legacy behaviour)

This way, we just reduce the number of SQL requests sent to the database and accelerate the import / export process.

Please let me know for your traces as the value should not be NULL.

**Comment by herve91** [comment]
closed as no information provided to investigate
