### ISSUE TITLE
Is it possible to load a database model from the command line?

### ISSUE THREAD

**Issue by gevaertw** [archi-contribs/database-plugin#84]
From what I found in the documentation the Archi command line does not seem to support interaction with the plugin.  Is this something that can be done?

This is my case:
I have a model that I want to access and manipulate using the command line tools to automate reports.  I don't have an on premise server where I can do that and I don't want it to run the reporting on my computer.  Therefore a central stored model in a cloud database, accessed by a small linux VM is to be preferred over a single Archi file stored on a computer.  
I could store the model on a cloud drive as an alternative, but then I have troubles getting the file from the cloud drive (OneDrive fro business) to that linux vm that runs Archi. (I do have a workaround but it is a dirty one IMO)

thanks!

**Comment by herve91** [comment]
Hi,

The script [script plugin](https://github.com/archi-contribs/script-plugin) has been developed for that usage.

**Comment by gevaertw** [comment]
Tnx

I will check it the next days...
