### ISSUE TITLE
Error on export to PostgreSQL

### ISSUE THREAD

**Issue by startsevsa** [archi-contribs/database-plugin#85]
Error happens on compare or trying to export (button)

Error text:
_Failed to export the model to the database.
The transaction has been rolled back to leave the database in coherent state. You may solve the issue and export again your components.

PSQLException: ERROR: prepared statement "S_1" already exists_

**Comment by startsevsa** [comment]
maybe the cause is in using the bouncer

**Comment by herve91** [comment]
Could you provide me with more information: version of Archi, version of the plugin and the last lines of the log file (the lines describing the SQL request sent to the database abd the Exception raised) ?

**Comment by herve91** [comment]
closed as no information to investigate
