### ISSUE TITLE
Null pointer exception on comparing model to DB

### ISSUE THREAD

**Issue by startsevsa** [archi-contribs/database-plugin#87]
ocurs when the shared elements is used in model.

error text:
_Failed to calculate the model's checksum.
The transaction has been rolled back to leave the database in coherent state. ...
NullPointerException_

**Comment by herve91** [comment]
Could you provide me with the end of the log file (the lines with the SQL request sent to the database and the exception raised) ?

**Comment by herve91** [comment]
closed as no information has been provided to investigate
