### ISSUE TITLE
Connect to Neo4j failing

### ISSUE THREAD

**Issue by MattiasLjung70** [archi-contribs/database-plugin#88]
Hi,

Don't know if related to this but I've upgraded to 2.2.3 but "Actual version" on Preferences page still says 2.2.2

My problem is the same as reported in #79 i.e. when configuring the Neo4j connection providing user name and psw the Check button returns "Database successfully tested"

But if I save, close down and reopens Preferences then username and psw has disappeared

I.e. user and psw seems not to be stored and therefore the export fails with authentication error

Br,
Mattias

**Comment by herve91** [comment]
Not linked to the version number badly reported.

I just sent the version 2.2.4 that fixes this issue.

Could you please confirm ?

**Comment by herve91** [comment]
I just sent the version 2.2.4 that fixes this issue.

Could you please confirm ?

**Comment by MattiasLjung70** [comment]
Hi,

"Actual version" is now showing correct value in Preferences but I still have the main issue 

I.e. user name and psw are not stored and used when connecting to neo4j, get authentication error

Tried with MS-SQL server and that works fine.

Update: solved the authentication issue by turning off authentication in Neo4j but now it turns out that none of the settings works when performing export i.e. "Export graph mode", "Empty database", ...

**Comment by herve91** [comment]
You can activate the log file in trace mode and edit your Neo4J database configuration.

Then in the log file, you'll have information about what is added in the preference store about your database and then check if the username and password are correctly saved and restored.

You can also check for messages logged during the connection phase:
   - Opening connection to database xxxxx
   - JDBC connection string = xxxxx
   - Connecting with username = xxxxx

**Comment by herve91** [comment]
fixed in version 2.2.5
