### ISSUE TITLE
GitHub rate limit exeeded

### ISSUE THREAD

**Issue by MPParsley** [archi-contribs/database-plugin#89]
When trying to update the plugin the following error occurs:

`IOException: Server returned HTTP response code: 403 for URL`

```
{
  "message": "API rate limit exceeded for x.x.x.x. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)",
  "documentation_url": "https://developer.github.com/v3/#rate-limiting"
}
```

There should be a way to configure a github token/api key.

**Comment by herve91** [comment]
The automatic update of the plugin does not work anymore. I'll remove it.
