### ISSUE TITLE
Cannot set up database plugin in preferences

### ISSUE THREAD

**Issue by LjsOks1** [archi-contribs/database-plugin#9]
Tried to configure a database link in Archi 4.0.0 using database plugin V2 but the link hasn't been created. In Preferences/database plugin I can fill up all the database properties but than what button should I press to save the settings?

Thanks,
Lajos

**Comment by LjsOks1** [comment]
Dear herve91,

Thanks for your prompt reply. Not sure what I'm doing wrong here...
I replaced the jar file with the alpha4 version from github but I don't have the cancel, save, check buttons on the configuration screen. I must be blind... enclosed a screenshot on what I see here and the about page so you can see the exact versions I'm working with.

Thanks a lot,
Lajos

![image](https://cloud.githubusercontent.com/assets/12964501/24445650/eb5e9d1a-146a-11e7-8360-d8872e006891.png)
![image](https://cloud.githubusercontent.com/assets/12964501/24445685/103437e4-146b-11e7-8bf9-14362a83db84.png)

**Comment by herve91** [comment]
Hi Lajos,

I effectively had a bug with with the "new" button. To be honnest, I mailny use the "edit" button and obviously did not check the "new" button thouroughly enough :(

I just uploaded a new JAR file that correct this specific bug but I did not change the release version number.

Please let me know ...

Thanks and regards
Hervé

**Comment by LjsOks1** [comment]
Dear Hervé,

Thanks a lot, it is working fine now.

Best Regards,
Lajos
