### ISSUE TITLE
Standalone vs Collaborative mode ?

### ISSUE THREAD

**Issue by BartCous** [archi-contribs/database-plugin#91]
Hi,

installed v2.2.5 on Archi 5.6.0, using Sql Server Express 2019. All goes very well. Great plugin. Thanks for sharing.

Have a question related to https://github.com/archi-contribs/database-plugin/wiki/4.-Exporting-a-model: how does the plugin decide to opt for standalone or collaborative mode ?

tia
Greetings from Belgium, Gent.

**Comment by herve91** [comment]
Hi,

Happy to know you appreciate my plugin. Unfortunately, I did not spent enough time on the documentation. As a result, the wiki is outdated. This part has not been updated from the version 1 of the plugin I'm afraid.

Basiclly, there is no standalone mode anymore. The current version of the plugin always compares the model to the database before exporting it. The disadvantage is that the export process is slower than it was in the version 1, but the advantage is that the export process is much more easier to code and therefore is more reliable.

Best regards
Hervé
