### ISSUE TITLE
v2.2.4  - Neo4j 4.0 bug?

### ISSUE THREAD

**Issue by sgg70** [archi-contribs/database-plugin#92]
(new to neo4j, got server set up just now, and managed to define a connection from Archi to Neo4j which "checks" ok in Archi)

I am wondering if there is an update required to support Neo4j v4.0 ?

...when trying to export a model, I get the error "Neo.Client.Error"... "old syntax {param} is no longer supported, please use $param instead"; happens when the plugin tries to send the CREATE statement, which contains multiple of the {} items...

![neo4jbug](https://user-images.githubusercontent.com/61889932/76124852-d75c6800-5fb8-11ea-9e99-528c9f02ca14.PNG)

**Comment by herve91** [comment]
Neo4J changed its syntax in version 4 ... I need to adapt my code.

I do not have much time at this moment but I add it to my todo list.

**Comment by normenmueller** [comment]
@herve91 Will there be support for Archi 4.6.0 <> Neo4j 4.x? Just asking. 

Maybe the error is on my site... but I just created a model in Archi with two nodes. But even the connection to Neo4j gives me an error:

![image](https://user-images.githubusercontent.com/428576/78986180-f5bf0180-7b2a-11ea-8e1e-0b41bbf48d6e.png)

**Comment by herve91** [comment]
Hi Normen,

My apologies for this long delay ... the situation is quite complicated at the moment.

This is not related to Archi 4.6 but to your Neo4J server version. I suppose that you installed Neo4J Server version 4.0.x but unfortunately the driver I embedded in my plugin is planned for Neo4J 3.x

So either you downgrade your Neo4J server to 3.5, either you wait few hours that I send a new release with updated drivers :)

Best regards
Hervé

**Comment by herve91** [comment]
@SGG70 Could you please try with plugin version 2.2.5 (new Neo4J driver) ?

**Comment by sgg70** [comment]
Yes, thank you! It works for me (updated the plugin in ARCHI, then reran same export as before -> moves across to neo4j without issues!)

**Comment by normenmueller** [comment]
@herve91 Sorry for the delay... kind of busy.

I installed v2.2.6 and configured a connection:
![image](https://user-images.githubusercontent.com/428576/81046770-60a8f180-8eb9-11ea-8a93-9c89ed9e8b0f.png)

And checked the connection
![image](https://user-images.githubusercontent.com/428576/81046807-71f1fe00-8eb9-11ea-9853-6bb88b8a08c6.png)

But then
![image](https://user-images.githubusercontent.com/428576/81046840-80d8b080-8eb9-11ea-955c-887f7cead3a8.png)

**Comment by herve91** [comment]
I succeeded to reproduce you issue: when the database is configured in "expert mode", the password is not stored in the preferences repository.

I'll fix it this afternoon and send an update today. Meanwhile, you can uncheck the "expert mode" flag and retype your database password. It will fix your issue.

**Comment by herve91** [comment]
Hi, version 2.2.7 fixes your issue.

**Comment by normenmueller** [comment]
Many thanks for the fast and good help! I could now export my model in Neo4j 4. Yes!
