### ISSUE TITLE
[Issue] Losing bend points after Import components (views) from database

### ISSUE THREAD

**Issue by rich-biker** [archi-contribs/database-plugin#93]
I've only just realised how good this database plugin is. Thanks for the great work. However, I'm losing relationship bendpoints.

***Versions***
Archi 4.6.0 Build 201911111111
OS: MacOS Catalina 10.15.3
Database Plug in Version 2.2.4
MySQL: 5.7.20 Community Server (GPL)

***Problem***
Question I'm importing views from a repository I've saved into a MySQL database, in order to pull in specific views for a HTML export. However, my views seem to loose any bendpoints so the relationships cut right across the new views. 

**Original**
![Screenshot 2020-03-13 at 15 17 20](https://user-images.githubusercontent.com/18450552/76634145-c7ef9880-653d-11ea-8fd8-72e4135bfcbc.png)

**Imported**
![Screenshot 2020-03-13 at 15 16 44](https://user-images.githubusercontent.com/18450552/76634161-cfaf3d00-653d-11ea-9340-20549291e67a.png)

**Comment by herve91** [comment]
I never experienced this issue and I do not have MAC anymore to do testing.

what I can suggest is that you create a test model with two elements and a single relationship between with one bendpoint. Then prior to export this test model to a test database, you do not forgot to switch the plugin to trace mode. At last, export your model, close it and import it back.

In the generated log file, you'll have the whole process that has been followed by the plugin and the error messages if any.

You may send it to me as well to analyse it.

The fist step would be to understand if the issue comes from the export or from the import.

**Comment by rich-biker** [comment]
I’ve finally got round to trying this out. In your simple use case it still straightened out the bend point on import of components. 

Log file (export mode) attached.

[DatabasePlugin ForHerve.log](https://github.com/archi-contribs/database-plugin/files/4376384/DatabasePlugin.ForHerve.log)

**Comment by herve91** [comment]
Your logfile is not really useful as it only contains INFO messages (I need TRACE ones to be able to investigate)

Nevertheless, I succeeded to get my MAC back and did some tests and fail to reproduce your issue. My simple test model is:
![image](https://user-images.githubusercontent.com/9281982/80319442-7dd22600-8810-11ea-84fb-c36617bd36e6.png)

The model exports successfully and is imported back successfully with all the bendpoints.

One thing you may check: in the "appearance" tab of the view, are you in "Manuel" or "Manhattan" ?
![image](https://user-images.githubusercontent.com/9281982/80319521-e9b48e80-8810-11ea-898d-536d99d5a797.png)

**Comment by edvardmokin** [comment]
Hello, the problems still exist and can be reproduced if you try to export only view from different model in DB. See log attached.

Archi version: 4.6.0
Build: 201911111111
DB Export/Import plugin : 2.2.5

Is there  an issue or any workaround ?

Two Screen shots below

![image](https://user-images.githubusercontent.com/54371319/80872305-0f152280-8c7f-11ea-9fa8-bd0047dbbf84.png)

![image](https://user-images.githubusercontent.com/54371319/80872312-176d5d80-8c7f-11ea-9256-782689ff1caa.png)


[DatabasePlugin.log](https://github.com/archi-contribs/database-plugin/files/4568499/DatabasePlugin.log)

**Comment by herve91** [comment]
Didn't understand it was during an import of a shared folder. I succeeded to reproduce your issue and found the bug.

It will be fixed in version 2.2.6.

I let you check and close the issue.

**Comment by edvardmokin** [comment]
version 2.2.7 fixed  the issue
