### ISSUE TITLE
Export to Neo4j issue: archimate relationships are transfered as nodes

### ISSUE THREAD

**Issue by harmverschuren** [archi-contribs/database-plugin#94]
Hello,

I have successfully exported an Archi model to Neo4j using the plugin. However, all archimate relation types are created as nodes with label "relationship" in Neo4j. Further, all relations are named "relatedTo". This results in search patterns like pseudo code: (my_ApplicationService)-[relatedTo]->(dummy:relationship:class = "RealizationRelation")-[relatedTo]->(my_ApplicationFunction).

From a GraphDB (Neo4j) perspective I would expect to get nodes only from the archimate-elements. Also I expect that relation types are transferred to relations between element-nodes, like:  (my_ApplicationService)-[REALIZATION]->(my_ApplicationFunction).

Is this a bug in the plugin or is my assumption wrong?

I am using Archi version 4.6.0 on Mac OS and a Neo4j sandbox hosted from https://sandbox.neo4j.com/.

Kind regards.

**Comment by herve91** [comment]
Sorry for this late answer, haven't been very available these days ...

In the database preference page, you can choose the relationship behaviour. Please select "use typed relationships".
![image](https://user-images.githubusercontent.com/9281982/78680012-3c261d80-78eb-11ea-8970-08fcffaf7b80.png)

**Comment by herve91** [comment]
Hi, does this fix your issue ?

**Comment by harmverschuren** [comment]
Hi @herve91, Sorry for the late response. I didn't get an email notification so was unaware of your comment. I will try within a few days and let you know.

**Comment by harmverschuren** [comment]
Hi @herve91 ,
I've tried both options and see the difference, but still not what I expected as in both cases it results in search patterns like pseudo code: 

`(my_ApplicationFunction)-[relatedTo]->(dummy:relationship:class = "RealizationRelation")-[relatedTo]->(my_ApplicationService)` 

instead of 

`(my_ApplicationFunction)-[REALIZATION]->(my_ApplicationService)` 

as example of a realisation relation between a function and a service.

I've add 2 screenprints of both options, perhaps that helps.

Figure 1: use typed relationships:
![result-use-typed-relationships](https://user-images.githubusercontent.com/31862080/80804477-98602280-8bb5-11ea-84d2-1e02b153cda5.png)

Figure 2: use unique relationship type:
![result-use-unique-relationship-type](https://user-images.githubusercontent.com/31862080/80804481-99914f80-8bb5-11ea-8ec0-cbfdc5f722bf.png)

**Comment by herve91** [comment]
Sorry, I misunderstood your question ...

Archi allows to create a relationship between relationships, while Neo4J doesn't.

Thus my plugin implements 2 modes for Neo4J:

- native: Archi relationships are created as Neo4J relationships but does not export Archi relationships that source or target another relationship
- extended: Archi relationships are created as Neo4J nodes so relationships that source or target another relationship can be exported

what you wish to achieved can be done with the following configuration:
![image](https://user-images.githubusercontent.com/9281982/80821008-3cf35c00-8bd8-11ea-91df-d3cd64838b86.png)

**Comment by harmverschuren** [comment]
Okay, thanks for the quick response. I'll give it a try.
  Kind regards.

**Comment by herve91** [comment]
Hi,

Did it solve your request ? Shall I close the issue ?

**Comment by harmverschuren** [comment]
Yes please.

Op do 2 jul. 2020 om 09:17 schreef Hervé Jouin <notifications@github.com>

**Comment by henrinickels** [comment]
Hello,
I am using Archi 4.8.0 with the Database export plugin version 2.2.13 and I encounter an issue with the NEO4J database type.

In fact, when I select the "Native", "Empty database..." and "Use typed..." options, they are not properly "saved" when the preferences are saved;
![image](https://user-images.githubusercontent.com/76954823/103543499-eb098100-4e9e-11eb-86be-d99b32269df1.png)

When I reopen the preferences, the basic settings selections "Extended", "Leave..." and "Use unique..." options remain selected:
![image](https://user-images.githubusercontent.com/76954823/103543541-fc528d80-4e9e-11eb-8427-b03f9989e001.png)

Any hint about the source/reason for this malfunction and where/how to resolve it?

**Comment by herve91** [comment]
This thread is closed. Please open a new one if you wish me to investigate.

Best regards
