### ISSUE TITLE
[feature request] Archi CLI support

### ISSUE THREAD

**Issue by WatchTh1** [archi-contribs/database-plugin#96]
Hello, @herve91 ! Do you have any plans to provide CLI api for database plugin? And if there is such feature where could I find a doc for it?

**Comment by herve91** [comment]
Hello,

I wrote a script plugin that allows to script the import a model from a database but it was before the CLI support of Archi. Since, I did not find the time to create a CLI interface.

I keep your request open but it won't be very soon I'm afraid.

Best regards
Hervé

**Comment by WatchTh1** [comment]
That's fine. I'm currently integrating model reporting into our corporate knowledge base by means of CI/CD tools.
Thus i'd like to make  a nice script to run model database export by some means.
Due to fact Archi has CLI I thought there is a commont way for every plugin to be called without GUI.

Request is not urgent, but makes a lot of things easier.
Thanks in advance and best regards, Alex.

**Comment by herve91** [comment]
version 2.2.8 adds CLI support:

> Archi [-consoleLog] -application com.archimatetool.commandline.app --import.database "database name" --import.model.name "model name" [--import.model.version "model version"]

When I have time, I'll add the ability to export a model to a database as well.

Best regards
Hervé
