### ISSUE TITLE
[bug] views_objects element_version is always null

### ISSUE THREAD

**Issue by WatchTh1** [archi-contribs/database-plugin#97]
Seems like after exporting into pgsql database field element_version is always empty, thus it is not possible to select unique element records from elements in a selected view when model has more than 1 version.
Example query:

create temp table elems  as 
	(
		select e2.* from elements e2  
			join elements_in_model eim on (eim.element_id = e2.id and eim.element_version = e2."version")
		where eim.model_version in (select max("version") from models)
		order by e2.id desc
);
create temp table voimver as 
(
		select vo.* from views_objects vo   
			join elems e on (e.id = vo.element_id )
			 
		order by vo.id desc
);
with tmp as (
select count(e.id) as c, v.id, v.element_id, v.element_version
from elems e
join voimver v on e.id = v.element_id
group  by e.id, v.id, v.element_id, v.element_version
)
select * from tmp
where c > 1

example result
2	_12ad61c5-7ea4-4295-ac10-686efc9b1bbf	_7660acf8-92e0-40b7-834b-0ef21f8a4a0f

**Comment by herve91** [comment]
I do not understand how the version column can by empty in your database as it is declared as "not null"

you can check the sql requests sent to your database by enabling the plugin log file, activate the "trace" level and checking that the "include SQL requests in trace mode" option is selected.

which version of Archi are you using and which version of the database plugin ?

**Comment by WatchTh1** [comment]
Yeah, I'll check out this thing through logging.
Archi version - 4.7 beta 4.
Plugin version - 2.2.7

**Comment by WatchTh1** [comment]
And i mean field element_version in table views_objects

**Comment by WatchTh1** [comment]
![image](https://user-images.githubusercontent.com/38937667/84875741-0c378b00-b08f-11ea-803a-11e7f2a81f7b.png)
Database scheme permits null values in this field.

**Comment by WatchTh1** [comment]
So this field is alwayes empty.
Here's insert example:
`
2020-06-17 12:17:25 TRACE  170:DBStatement                              -       --> INSERT INTO public.views_objects_in_view (object_id, object_version, view_id, view_version, rank) VALUES ('70c6a201-9e4e-4578-b830-5c12da1e8cca', 1, '754cc82b-61e3-4665-b5ff-c664571d35a3', 2, 1)
`

**Comment by herve91** [comment]
First, I didn't get you were talking about the views_object table.

In this table, the element_id is not null when the object refers to an Archimate element, and is null when the object does not refer to an Archimate element (like a note or a group), and the element_version is not used as you can see in the SQL request. It was a test to fix the version of an element in a view when the view is created outside of Archi, but it led to issues when loading the view when another version of the element was already present in the model. I kept the column but you cannot rely on it.

**Comment by WatchTh1** [comment]
How do you then distinguish views_object versions amongst model versions ?

**Comment by herve91** [comment]
All the model components are referenced by a coucle id + version:
   - elements are stored in the elements table and are referenced by the couple id + version
   - relationships are referenced in the relationships table referenced by the couple id + version
   - and so on ...

Then you've got additional tables that links those components together:
   - elements_in_model list the elements (referenced by the couple element_id+element_version) in each model (referenced by the couple model_id+model_version)
   - relationshipls_in_model list the relationships (referenced by the couple relationship_id+relationship_version) in each model (referenced by the couple model_id+model_version)
   - and so on ...

The view objects are linked to their view through the table views_objects_in_view, and the views are linked to their model through the table views_in_model.

The database structure is described here : https://github.com/archi-contribs/database-plugin/tree/master/v2/database%20structure

**Comment by WatchTh1** [comment]
Yeah, thanks constructed necessary query. That helped a lot.
