### ISSUE TITLE
[enhancement] Support Archi 4.7

### ISSUE THREAD

**Issue by WatchTh1** [archi-contribs/database-plugin#98]
Seems like with new version some interface features have become broken. Like flags.

![image](https://user-images.githubusercontent.com/38937667/85298082-4bf5dc80-b4ac-11ea-8a9e-32f42a178b85.png)

t450s@t450s:~$ java -version
openjdk version "1.8.0_252"
OpenJDK Runtime Environment (build 1.8.0_252-8u252-b09-1ubuntu1-b09)
OpenJDK 64-Bit Server VM (build 25.252-b09, mixed mode)

Archi version: 4.7.0 beta 5

**Comment by herve91** [comment]
Archi 4.7 is still in beta versio and the database plugin is effectively not compatible.

I'll release a new version ofthe database plugin in the coming weeks.

**Comment by WatchTh1** [comment]
Thanks, waiting a lot.

**Comment by herve91** [comment]
I just re-read your message and I'm quite puzzled ...

Archi 4.7 uses Java 11:
[herve@centos ~]$ Archi/jre/bin/java -version
openjdk version "11.0.3" 2019-04-16
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.3+7)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.3+7, mixed mode)

Flags are present as expected on my test VM with centOS:
![image](https://user-images.githubusercontent.com/9281982/86248010-91519280-bbad-11ea-97f0-67c5cf55aaea.png)

**Comment by WatchTh1** [comment]
With 
t450s@t450s:~/.themes$ java -version
openjdk version "11.0.7" 2020-04-14
OpenJDK Runtime Environment (build 11.0.7+10-post-Ubuntu-3ubuntu1)
OpenJDK 64-Bit Server VM (build 11.0.7+10-post-Ubuntu-3ubuntu1, mixed mode, sharing)

issue has been fixed. 
Thanks for your support!

**Comment by herve91** [comment]
Good news. I close the issue.
