### ISSUE TITLE
Cannot admin the database

### ISSUE THREAD

**Issue by edvardmokin** [archi-contribs/database-plugin#99]
Using Archi 4.7, Database plugin 2.2.7

When click Admin get an error - "Cannot admin the database"

Main reason looking this feature to be able to delete unused Models. Log attached.

![image](https://user-images.githubusercontent.com/54371319/86365606-ba266600-bc47-11ea-86f8-d947d3b03f0b.png)
[DatabasePlugin.log](https://github.com/archi-contribs/database-plugin/files/4864597/DatabasePlugin.log)

**Comment by herve91** [comment]
Hi,

In fact, this error is not linked to the vesion of Archi and already exists when my plugin is ran under Archi 4.6.

Nevertheless, the delete feature is not yet developped so you won't find it here. At the moment, the only way to delete a model is to run a SQL request in your database as explained in your other post #100 

Even if this nullPointerException is already a known issue, I keep your post open until it is solved.

**Comment by herve91** [comment]
version 2.2.8 fixes the Exception issue.

Best regards
Hervé
